// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.36516
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLasyLoading>False</EnableLasyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nocore.nl/2010-10")]
    [System.Xml.Serialization.XmlRootAttribute("NocoreResume", Namespace = "http://www.nocore.nl/2010-10", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NocoreResumeType", Namespace = "http://www.nocore.nl/2010-10")]
    public partial class NocoreResumeType : EntityBase<NocoreResumeType>
    {

        private List<AvailibilityType> availabilityField;

        private decimal hoursPerWeekAvailableField;

        private bool hoursPerWeekAvailableFieldSpecified;

        private DesiredWorkType desiredWorkField;

        /// <summary>
        /// NocoreResumeType class constructor
        /// </summary>
        public NocoreResumeType()
        {
            this.desiredWorkField = new DesiredWorkType();
            this.availabilityField = new List<AvailibilityType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Availability")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<AvailibilityType> Availability
        {
            get
            {
                return this.availabilityField;
            }
            set
            {
                if ((this.availabilityField != null))
                {
                    if ((availabilityField.Equals(value) != true))
                    {
                        this.availabilityField = value;
                        this.OnPropertyChanged("Availability");
                    }
                }
                else
                {
                    this.availabilityField = value;
                    this.OnPropertyChanged("Availability");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal HoursPerWeekAvailable
        {
            get
            {
                return this.hoursPerWeekAvailableField;
            }
            set
            {
                if ((hoursPerWeekAvailableField.Equals(value) != true))
                {
                    this.hoursPerWeekAvailableField = value;
                    this.OnPropertyChanged("HoursPerWeekAvailable");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HoursPerWeekAvailableSpecified
        {
            get
            {
                return this.hoursPerWeekAvailableFieldSpecified;
            }
            set
            {
                if ((hoursPerWeekAvailableFieldSpecified.Equals(value) != true))
                {
                    this.hoursPerWeekAvailableFieldSpecified = value;
                    this.OnPropertyChanged("HoursPerWeekAvailableSpecified");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public DesiredWorkType DesiredWork
        {
            get
            {
                return this.desiredWorkField;
            }
            set
            {
                if ((this.desiredWorkField != null))
                {
                    if ((desiredWorkField.Equals(value) != true))
                    {
                        this.desiredWorkField = value;
                        this.OnPropertyChanged("DesiredWork");
                    }
                }
                else
                {
                    this.desiredWorkField = value;
                    this.OnPropertyChanged("DesiredWork");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nocore.nl/2010-10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AvailibilityType", Namespace = "http://www.nocore.nl/2010-10")]
    public partial class AvailibilityType : EntityBase<AvailibilityType>
    {

        private System.DateTime startDateField;

        private System.DateTime endDateField;

        private bool endDateFieldSpecified;

        private DayOfWeekType dayOfWeekField;

        private PartOfDayType partOfDayField;

        private AvailabilityStatusType availabilityStatusField;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                if ((startDateField.Equals(value) != true))
                {
                    this.startDateField = value;
                    this.OnPropertyChanged("StartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                if ((endDateField.Equals(value) != true))
                {
                    this.endDateField = value;
                    this.OnPropertyChanged("EndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EndDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                if ((endDateFieldSpecified.Equals(value) != true))
                {
                    this.endDateFieldSpecified = value;
                    this.OnPropertyChanged("EndDateSpecified");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public DayOfWeekType DayOfWeek
        {
            get
            {
                return this.dayOfWeekField;
            }
            set
            {
                if ((dayOfWeekField.Equals(value) != true))
                {
                    this.dayOfWeekField = value;
                    this.OnPropertyChanged("DayOfWeek");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartOfDayType PartOfDay
        {
            get
            {
                return this.partOfDayField;
            }
            set
            {
                if ((partOfDayField.Equals(value) != true))
                {
                    this.partOfDayField = value;
                    this.OnPropertyChanged("PartOfDay");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AvailabilityStatusType AvailabilityStatus
        {
            get
            {
                return this.availabilityStatusField;
            }
            set
            {
                if ((availabilityStatusField.Equals(value) != true))
                {
                    this.availabilityStatusField = value;
                    this.OnPropertyChanged("AvailabilityStatus");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nocore.nl/2010-10")]
    public enum DayOfWeekType
    {

        /// <remarks/>
        Monday,

        /// <remarks/>
        Tuesday,

        /// <remarks/>
        Wednesday,

        /// <remarks/>
        Thursday,

        /// <remarks/>
        Friday,

        /// <remarks/>
        Saturday,

        /// <remarks/>
        Sunday,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nocore.nl/2010-10")]
    public enum PartOfDayType
    {

        /// <remarks/>
        Morning,

        /// <remarks/>
        Afternoon,

        /// <remarks/>
        Evening,

        /// <remarks/>
        Night,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nocore.nl/2010-10")]
    public enum AvailabilityStatusType
    {

        /// <remarks/>
        Available,

        /// <remarks/>
        Unavailable,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nocore.nl/2010-10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "StructuredDesiredWorkType", Namespace = "http://www.nocore.nl/2010-10")]
    public partial class StructuredDesiredWorkType : EntityBase<StructuredDesiredWorkType>
    {

        private List<EntityIdType> desiredWorkIdField;

        private string desiredWorkField;

        /// <summary>
        /// StructuredDesiredWorkType class constructor
        /// </summary>
        public StructuredDesiredWorkType()
        {
            this.desiredWorkIdField = new List<EntityIdType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("DesiredWorkId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> DesiredWorkId
        {
            get
            {
                return this.desiredWorkIdField;
            }
            set
            {
                if ((this.desiredWorkIdField != null))
                {
                    if ((desiredWorkIdField.Equals(value) != true))
                    {
                        this.desiredWorkIdField = value;
                        this.OnPropertyChanged("DesiredWorkId");
                    }
                }
                else
                {
                    this.desiredWorkIdField = value;
                    this.OnPropertyChanged("DesiredWorkId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesiredWork
        {
            get
            {
                return this.desiredWorkField;
            }
            set
            {
                if ((this.desiredWorkField != null))
                {
                    if ((desiredWorkField.Equals(value) != true))
                    {
                        this.desiredWorkField = value;
                        this.OnPropertyChanged("DesiredWork");
                    }
                }
                else
                {
                    this.desiredWorkField = value;
                    this.OnPropertyChanged("DesiredWork");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nocore.nl/2010-10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DesiredWorkType", Namespace = "http://www.nocore.nl/2010-10")]
    public partial class DesiredWorkType : EntityBase<DesiredWorkType>
    {

        private List<StructuredDesiredWorkType> itemsField;

        private string descriptionField;

        /// <summary>
        /// DesiredWorkType class constructor
        /// </summary>
        public DesiredWorkType()
        {
            this.itemsField = new List<StructuredDesiredWorkType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Items")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<StructuredDesiredWorkType> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                if ((this.itemsField != null))
                {
                    if ((itemsField.Equals(value) != true))
                    {
                        this.itemsField = value;
                        this.OnPropertyChanged("Items");
                    }
                }
                else
                {
                    this.itemsField = value;
                    this.OnPropertyChanged("Items");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                if ((this.descriptionField != null))
                {
                    if ((descriptionField.Equals(value) != true))
                    {
                        this.descriptionField = value;
                        this.OnPropertyChanged("Description");
                    }
                }
                else
                {
                    this.descriptionField = value;
                    this.OnPropertyChanged("Description");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nocore.nl/2010-10")]
    [System.Xml.Serialization.XmlRootAttribute("NocorePositionHistory", Namespace = "http://www.nocore.nl/2010-10", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NocorePositionHistoryType", Namespace = "http://www.nocore.nl/2010-10")]
    public partial class NocorePositionHistoryType : EntityBase<NocorePositionHistoryType>
    {

        private List<EntityIdType> positionHistoryIdField;

        /// <summary>
        /// NocorePositionHistoryType class constructor
        /// </summary>
        public NocorePositionHistoryType()
        {
            this.positionHistoryIdField = new List<EntityIdType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("PositionHistoryId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> PositionHistoryId
        {
            get
            {
                return this.positionHistoryIdField;
            }
            set
            {
                if ((this.positionHistoryIdField != null))
                {
                    if ((positionHistoryIdField.Equals(value) != true))
                    {
                        this.positionHistoryIdField = value;
                        this.OnPropertyChanged("PositionHistoryId");
                    }
                }
                else
                {
                    this.positionHistoryIdField = value;
                    this.OnPropertyChanged("PositionHistoryId");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nocore.nl/2010-10")]
    [System.Xml.Serialization.XmlRootAttribute("NocoreSchoolOrInstitution", Namespace = "http://www.nocore.nl/2010-10", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NocoreSchoolOrInstitutionType", Namespace = "http://www.nocore.nl/2010-10")]
    public partial class NocoreSchoolOrInstitutionType : EntityBase<NocoreSchoolOrInstitutionType>
    {

        private List<EntityIdType> schoolOrInstitutionIdField;

        /// <summary>
        /// NocoreSchoolOrInstitutionType class constructor
        /// </summary>
        public NocoreSchoolOrInstitutionType()
        {
            this.schoolOrInstitutionIdField = new List<EntityIdType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("SchoolOrInstitutionId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> SchoolOrInstitutionId
        {
            get
            {
                return this.schoolOrInstitutionIdField;
            }
            set
            {
                if ((this.schoolOrInstitutionIdField != null))
                {
                    if ((schoolOrInstitutionIdField.Equals(value) != true))
                    {
                        this.schoolOrInstitutionIdField = value;
                        this.OnPropertyChanged("SchoolOrInstitutionId");
                    }
                }
                else
                {
                    this.schoolOrInstitutionIdField = value;
                    this.OnPropertyChanged("SchoolOrInstitutionId");
                }
            }
        }
    }
}
