// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.33213
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PersonLegalIdType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class PersonLegalIdType : EntityIdType, System.ComponentModel.INotifyPropertyChanged
    {

        private string countryCodeField;

        private string jurisdictionField;

        private string issuingRegionField;

        private string documentTypeField;

        private string idSourceField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                if ((this.countryCodeField != null))
                {
                    if ((countryCodeField.Equals(value) != true))
                    {
                        this.countryCodeField = value;
                        this.OnPropertyChanged("countryCode");
                    }
                }
                else
                {
                    this.countryCodeField = value;
                    this.OnPropertyChanged("countryCode");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jurisdiction
        {
            get
            {
                return this.jurisdictionField;
            }
            set
            {
                if ((this.jurisdictionField != null))
                {
                    if ((jurisdictionField.Equals(value) != true))
                    {
                        this.jurisdictionField = value;
                        this.OnPropertyChanged("jurisdiction");
                    }
                }
                else
                {
                    this.jurisdictionField = value;
                    this.OnPropertyChanged("jurisdiction");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string issuingRegion
        {
            get
            {
                return this.issuingRegionField;
            }
            set
            {
                if ((this.issuingRegionField != null))
                {
                    if ((issuingRegionField.Equals(value) != true))
                    {
                        this.issuingRegionField = value;
                        this.OnPropertyChanged("issuingRegion");
                    }
                }
                else
                {
                    this.issuingRegionField = value;
                    this.OnPropertyChanged("issuingRegion");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                if ((this.documentTypeField != null))
                {
                    if ((documentTypeField.Equals(value) != true))
                    {
                        this.documentTypeField = value;
                        this.OnPropertyChanged("documentType");
                    }
                }
                else
                {
                    this.documentTypeField = value;
                    this.OnPropertyChanged("documentType");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idSource
        {
            get
            {
                return this.idSourceField;
            }
            set
            {
                if ((this.idSourceField != null))
                {
                    if ((idSourceField.Equals(value) != true))
                    {
                        this.idSourceField = value;
                        this.OnPropertyChanged("idSource");
                    }
                }
                else
                {
                    this.idSourceField = value;
                    this.OnPropertyChanged("idSource");
                }
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DisabilityInfoType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class DisabilityInfoType : EntityBase<DisabilityInfoType>
    {

        private string levelOfDisabilityField;

        private string percentageField;

        private string typeField;

        private bool accommodationsNeededField;

        private bool accommodationsNeededFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LevelOfDisability
        {
            get
            {
                return this.levelOfDisabilityField;
            }
            set
            {
                if ((this.levelOfDisabilityField != null))
                {
                    if ((levelOfDisabilityField.Equals(value) != true))
                    {
                        this.levelOfDisabilityField = value;
                        this.OnPropertyChanged("LevelOfDisability");
                    }
                }
                else
                {
                    this.levelOfDisabilityField = value;
                    this.OnPropertyChanged("LevelOfDisability");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Percentage
        {
            get
            {
                return this.percentageField;
            }
            set
            {
                if ((this.percentageField != null))
                {
                    if ((percentageField.Equals(value) != true))
                    {
                        this.percentageField = value;
                        this.OnPropertyChanged("Percentage");
                    }
                }
                else
                {
                    this.percentageField = value;
                    this.OnPropertyChanged("Percentage");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                if ((this.typeField != null))
                {
                    if ((typeField.Equals(value) != true))
                    {
                        this.typeField = value;
                        this.OnPropertyChanged("Type");
                    }
                }
                else
                {
                    this.typeField = value;
                    this.OnPropertyChanged("Type");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AccommodationsNeeded
        {
            get
            {
                return this.accommodationsNeededField;
            }
            set
            {
                if ((accommodationsNeededField.Equals(value) != true))
                {
                    this.accommodationsNeededField = value;
                    this.OnPropertyChanged("AccommodationsNeeded");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AccommodationsNeededSpecified
        {
            get
            {
                return this.accommodationsNeededFieldSpecified;
            }
            set
            {
                if ((accommodationsNeededFieldSpecified.Equals(value) != true))
                {
                    this.accommodationsNeededFieldSpecified = value;
                    this.OnPropertyChanged("AccommodationsNeededSpecified");
                }
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentCompetencyReferenceType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentCompetencyReferenceType : SpecifiedCompetencyReferenceType, System.ComponentModel.INotifyPropertyChanged
    {

        private string competencyNameField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompetencyName
        {
            get
            {
                return this.competencyNameField;
            }
            set
            {
                if ((this.competencyNameField != null))
                {
                    if ((competencyNameField.Equals(value) != true))
                    {
                        this.competencyNameField = value;
                        this.OnPropertyChanged("CompetencyName");
                    }
                }
                else
                {
                    this.competencyNameField = value;
                    this.OnPropertyChanged("CompetencyName");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentStatusType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentStatusType : EntityBase<AssessmentStatusType>
    {

        private AssessmentStatusTypeStatus statusField;

        private string detailsField;

        private string statusDateField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssessmentStatusTypeStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                if ((statusField.Equals(value) != true))
                {
                    this.statusField = value;
                    this.OnPropertyChanged("Status");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                if ((this.detailsField != null))
                {
                    if ((detailsField.Equals(value) != true))
                    {
                        this.detailsField = value;
                        this.OnPropertyChanged("Details");
                    }
                }
                else
                {
                    this.detailsField = value;
                    this.OnPropertyChanged("Details");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDate
        {
            get
            {
                return this.statusDateField;
            }
            set
            {
                if ((this.statusDateField != null))
                {
                    if ((statusDateField.Equals(value) != true))
                    {
                        this.statusDateField = value;
                        this.OnPropertyChanged("StatusDate");
                    }
                }
                else
                {
                    this.statusDateField = value;
                    this.OnPropertyChanged("StatusDate");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum AssessmentStatusTypeStatus
    {

        /// <remarks/>
        Pending,

        /// <remarks/>
        Error,

        /// <remarks/>
        Acknowledged,

        /// <remarks/>
        Scheduled,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Progress")]
        InProgress,

        /// <remarks/>
        Cancelled,

        /// <remarks/>
        Declined,

        /// <remarks/>
        Completed,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("x:Deferred")]
        xDeferred,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentRequestType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentRequestType : EntityBase<AssessmentRequestType>
    {

        private EntityIdType clientIdField;

        private EntityIdType providerIdField;

        private EntityIdType clientOrderIdField;

        private EntityIdType receiptIdField;

        private UserAreaType userAreaField;

        /// <summary>
        /// AssessmentRequestType class constructor
        /// </summary>
        public AssessmentRequestType()
        {
            this.userAreaField = new UserAreaType();
            this.receiptIdField = new EntityIdType();
            this.clientOrderIdField = new EntityIdType();
            this.providerIdField = new EntityIdType();
            this.clientIdField = new EntityIdType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType ClientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                if ((this.clientIdField != null))
                {
                    if ((clientIdField.Equals(value) != true))
                    {
                        this.clientIdField = value;
                        this.OnPropertyChanged("ClientId");
                    }
                }
                else
                {
                    this.clientIdField = value;
                    this.OnPropertyChanged("ClientId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType ProviderId
        {
            get
            {
                return this.providerIdField;
            }
            set
            {
                if ((this.providerIdField != null))
                {
                    if ((providerIdField.Equals(value) != true))
                    {
                        this.providerIdField = value;
                        this.OnPropertyChanged("ProviderId");
                    }
                }
                else
                {
                    this.providerIdField = value;
                    this.OnPropertyChanged("ProviderId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType ClientOrderId
        {
            get
            {
                return this.clientOrderIdField;
            }
            set
            {
                if ((this.clientOrderIdField != null))
                {
                    if ((clientOrderIdField.Equals(value) != true))
                    {
                        this.clientOrderIdField = value;
                        this.OnPropertyChanged("ClientOrderId");
                    }
                }
                else
                {
                    this.clientOrderIdField = value;
                    this.OnPropertyChanged("ClientOrderId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType ReceiptId
        {
            get
            {
                return this.receiptIdField;
            }
            set
            {
                if ((this.receiptIdField != null))
                {
                    if ((receiptIdField.Equals(value) != true))
                    {
                        this.receiptIdField = value;
                        this.OnPropertyChanged("ReceiptId");
                    }
                }
                else
                {
                    this.receiptIdField = value;
                    this.OnPropertyChanged("ReceiptId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAreaType UserArea
        {
            get
            {
                return this.userAreaField;
            }
            set
            {
                if ((this.userAreaField != null))
                {
                    if ((userAreaField.Equals(value) != true))
                    {
                        this.userAreaField = value;
                        this.OnPropertyChanged("UserArea");
                    }
                }
                else
                {
                    this.userAreaField = value;
                    this.OnPropertyChanged("UserArea");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AdministrationInfoType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AdministrationInfoType : EntityBase<AdministrationInfoType>
    {

        private string administrationNotesField;

        private bool isProctoredField;

        private bool isProctoredFieldSpecified;

        private AdministrationInfoTypeTimeEnforcement timeEnforcementField;

        private string estimatedTimeField;

        private List<AdministrationInfoTypeAssessmentDelivery> assessmentDeliveryField;

        /// <summary>
        /// AdministrationInfoType class constructor
        /// </summary>
        public AdministrationInfoType()
        {
            this.assessmentDeliveryField = new List<AdministrationInfoTypeAssessmentDelivery>();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdministrationNotes
        {
            get
            {
                return this.administrationNotesField;
            }
            set
            {
                if ((this.administrationNotesField != null))
                {
                    if ((administrationNotesField.Equals(value) != true))
                    {
                        this.administrationNotesField = value;
                        this.OnPropertyChanged("AdministrationNotes");
                    }
                }
                else
                {
                    this.administrationNotesField = value;
                    this.OnPropertyChanged("AdministrationNotes");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProctored
        {
            get
            {
                return this.isProctoredField;
            }
            set
            {
                if ((isProctoredField.Equals(value) != true))
                {
                    this.isProctoredField = value;
                    this.OnPropertyChanged("IsProctored");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProctoredSpecified
        {
            get
            {
                return this.isProctoredFieldSpecified;
            }
            set
            {
                if ((isProctoredFieldSpecified.Equals(value) != true))
                {
                    this.isProctoredFieldSpecified = value;
                    this.OnPropertyChanged("IsProctoredSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdministrationInfoTypeTimeEnforcement TimeEnforcement
        {
            get
            {
                return this.timeEnforcementField;
            }
            set
            {
                if ((timeEnforcementField.Equals(value) != true))
                {
                    this.timeEnforcementField = value;
                    this.OnPropertyChanged("TimeEnforcement");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstimatedTime
        {
            get
            {
                return this.estimatedTimeField;
            }
            set
            {
                if ((this.estimatedTimeField != null))
                {
                    if ((estimatedTimeField.Equals(value) != true))
                    {
                        this.estimatedTimeField = value;
                        this.OnPropertyChanged("EstimatedTime");
                    }
                }
                else
                {
                    this.estimatedTimeField = value;
                    this.OnPropertyChanged("EstimatedTime");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AssessmentDelivery", Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<AdministrationInfoTypeAssessmentDelivery> AssessmentDelivery
        {
            get
            {
                return this.assessmentDeliveryField;
            }
            set
            {
                if ((this.assessmentDeliveryField != null))
                {
                    if ((assessmentDeliveryField.Equals(value) != true))
                    {
                        this.assessmentDeliveryField = value;
                        this.OnPropertyChanged("AssessmentDelivery");
                    }
                }
                else
                {
                    this.assessmentDeliveryField = value;
                    this.OnPropertyChanged("AssessmentDelivery");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum AdministrationInfoTypeTimeEnforcement
    {

        /// <remarks/>
        None,

        /// <remarks/>
        Partial,

        /// <remarks/>
        Complete,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AdministrationInfoTypeAssessmentDelivery", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AdministrationInfoTypeAssessmentDelivery : EntityBase<AdministrationInfoTypeAssessmentDelivery>
    {

        private bool schedulingRequiredField;

        private bool schedulingRequiredFieldSpecified;

        private AssessmentDeliveryTypes valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool schedulingRequired
        {
            get
            {
                return this.schedulingRequiredField;
            }
            set
            {
                if ((schedulingRequiredField.Equals(value) != true))
                {
                    this.schedulingRequiredField = value;
                    this.OnPropertyChanged("schedulingRequired");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool schedulingRequiredSpecified
        {
            get
            {
                return this.schedulingRequiredFieldSpecified;
            }
            set
            {
                if ((schedulingRequiredFieldSpecified.Equals(value) != true))
                {
                    this.schedulingRequiredFieldSpecified = value;
                    this.OnPropertyChanged("schedulingRequiredSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssessmentDeliveryTypes Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((valueField.Equals(value) != true))
                {
                    this.valueField = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum AssessmentDeliveryTypes
    {

        /// <remarks/>
        online,

        /// <remarks/>
        telephone,

        /// <remarks/>
        mail,

        /// <remarks/>
        fax,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResultInfoType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class ResultInfoType : EntityBase<ResultInfoType>
    {

        private string resultProfileField;

        private string descriptionField;

        private string resultLanguageField;

        private System.DateTime validToField;

        private bool validToFieldSpecified;

        private System.DateTime validFromField;

        private bool validFromFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultProfile
        {
            get
            {
                return this.resultProfileField;
            }
            set
            {
                if ((this.resultProfileField != null))
                {
                    if ((resultProfileField.Equals(value) != true))
                    {
                        this.resultProfileField = value;
                        this.OnPropertyChanged("ResultProfile");
                    }
                }
                else
                {
                    this.resultProfileField = value;
                    this.OnPropertyChanged("ResultProfile");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                if ((this.descriptionField != null))
                {
                    if ((descriptionField.Equals(value) != true))
                    {
                        this.descriptionField = value;
                        this.OnPropertyChanged("Description");
                    }
                }
                else
                {
                    this.descriptionField = value;
                    this.OnPropertyChanged("Description");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "language", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultLanguage
        {
            get
            {
                return this.resultLanguageField;
            }
            set
            {
                if ((this.resultLanguageField != null))
                {
                    if ((resultLanguageField.Equals(value) != true))
                    {
                        this.resultLanguageField = value;
                        this.OnPropertyChanged("ResultLanguage");
                    }
                }
                else
                {
                    this.resultLanguageField = value;
                    this.OnPropertyChanged("ResultLanguage");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime validTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                if ((validToField.Equals(value) != true))
                {
                    this.validToField = value;
                    this.OnPropertyChanged("validTo");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool validToSpecified
        {
            get
            {
                return this.validToFieldSpecified;
            }
            set
            {
                if ((validToFieldSpecified.Equals(value) != true))
                {
                    this.validToFieldSpecified = value;
                    this.OnPropertyChanged("validToSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime validFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                if ((validFromField.Equals(value) != true))
                {
                    this.validFromField = value;
                    this.OnPropertyChanged("validFrom");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool validFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                if ((validFromFieldSpecified.Equals(value) != true))
                {
                    this.validFromFieldSpecified = value;
                    this.OnPropertyChanged("validFromSpecified");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "IsTimeEnforcedType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class IsTimeEnforcedType : EntityBase<IsTimeEnforcedType>
    {

        private string maxTimeAllowedField;

        private bool valueField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "duration")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maxTimeAllowed
        {
            get
            {
                return this.maxTimeAllowedField;
            }
            set
            {
                if ((this.maxTimeAllowedField != null))
                {
                    if ((maxTimeAllowedField.Equals(value) != true))
                    {
                        this.maxTimeAllowedField = value;
                        this.OnPropertyChanged("maxTimeAllowed");
                    }
                }
                else
                {
                    this.maxTimeAllowedField = value;
                    this.OnPropertyChanged("maxTimeAllowed");
                }
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((valueField.Equals(value) != true))
                {
                    this.valueField = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentPackageType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentPackageType : EntityBase<AssessmentPackageType>
    {

        private EntityIdType packageIdField;

        private List<EntityIdType> packageGroupIdField;

        private string nameField;

        private string descriptionField;

        private string pricingInfoField;

        private AdministrationInfoType administrationInfoField;

        private List<ResultInfoType> resultInfoField;

        private AssessmentApplicabilityType applicabilityField;

        private UserAreaType userAreaField;

        private string validFromField;

        private string validToField;

        /// <summary>
        /// AssessmentPackageType class constructor
        /// </summary>
        public AssessmentPackageType()
        {
            this.userAreaField = new UserAreaType();
            this.applicabilityField = new AssessmentApplicabilityType();
            this.resultInfoField = new List<ResultInfoType>();
            this.administrationInfoField = new AdministrationInfoType();
            this.packageGroupIdField = new List<EntityIdType>();
            this.packageIdField = new EntityIdType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType PackageId
        {
            get
            {
                return this.packageIdField;
            }
            set
            {
                if ((this.packageIdField != null))
                {
                    if ((packageIdField.Equals(value) != true))
                    {
                        this.packageIdField = value;
                        this.OnPropertyChanged("PackageId");
                    }
                }
                else
                {
                    this.packageIdField = value;
                    this.OnPropertyChanged("PackageId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("PackageGroupId", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> PackageGroupId
        {
            get
            {
                return this.packageGroupIdField;
            }
            set
            {
                if ((this.packageGroupIdField != null))
                {
                    if ((packageGroupIdField.Equals(value) != true))
                    {
                        this.packageGroupIdField = value;
                        this.OnPropertyChanged("PackageGroupId");
                    }
                }
                else
                {
                    this.packageGroupIdField = value;
                    this.OnPropertyChanged("PackageGroupId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("Name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                if ((this.descriptionField != null))
                {
                    if ((descriptionField.Equals(value) != true))
                    {
                        this.descriptionField = value;
                        this.OnPropertyChanged("Description");
                    }
                }
                else
                {
                    this.descriptionField = value;
                    this.OnPropertyChanged("Description");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PricingInfo
        {
            get
            {
                return this.pricingInfoField;
            }
            set
            {
                if ((this.pricingInfoField != null))
                {
                    if ((pricingInfoField.Equals(value) != true))
                    {
                        this.pricingInfoField = value;
                        this.OnPropertyChanged("PricingInfo");
                    }
                }
                else
                {
                    this.pricingInfoField = value;
                    this.OnPropertyChanged("PricingInfo");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdministrationInfoType AdministrationInfo
        {
            get
            {
                return this.administrationInfoField;
            }
            set
            {
                if ((this.administrationInfoField != null))
                {
                    if ((administrationInfoField.Equals(value) != true))
                    {
                        this.administrationInfoField = value;
                        this.OnPropertyChanged("AdministrationInfo");
                    }
                }
                else
                {
                    this.administrationInfoField = value;
                    this.OnPropertyChanged("AdministrationInfo");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ResultInfo", Order = 6)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ResultInfoType> ResultInfo
        {
            get
            {
                return this.resultInfoField;
            }
            set
            {
                if ((this.resultInfoField != null))
                {
                    if ((resultInfoField.Equals(value) != true))
                    {
                        this.resultInfoField = value;
                        this.OnPropertyChanged("ResultInfo");
                    }
                }
                else
                {
                    this.resultInfoField = value;
                    this.OnPropertyChanged("ResultInfo");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssessmentApplicabilityType Applicability
        {
            get
            {
                return this.applicabilityField;
            }
            set
            {
                if ((this.applicabilityField != null))
                {
                    if ((applicabilityField.Equals(value) != true))
                    {
                        this.applicabilityField = value;
                        this.OnPropertyChanged("Applicability");
                    }
                }
                else
                {
                    this.applicabilityField = value;
                    this.OnPropertyChanged("Applicability");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAreaType UserArea
        {
            get
            {
                return this.userAreaField;
            }
            set
            {
                if ((this.userAreaField != null))
                {
                    if ((userAreaField.Equals(value) != true))
                    {
                        this.userAreaField = value;
                        this.OnPropertyChanged("UserArea");
                    }
                }
                else
                {
                    this.userAreaField = value;
                    this.OnPropertyChanged("UserArea");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string validFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                if ((this.validFromField != null))
                {
                    if ((validFromField.Equals(value) != true))
                    {
                        this.validFromField = value;
                        this.OnPropertyChanged("validFrom");
                    }
                }
                else
                {
                    this.validFromField = value;
                    this.OnPropertyChanged("validFrom");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string validTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                if ((this.validToField != null))
                {
                    if ((validToField.Equals(value) != true))
                    {
                        this.validToField = value;
                        this.OnPropertyChanged("validTo");
                    }
                }
                else
                {
                    this.validToField = value;
                    this.OnPropertyChanged("validTo");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentApplicabilityType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentApplicabilityType : EntityBase<AssessmentApplicabilityType>
    {

        private List<AssessmentCompetencyReferenceType> competencyAssessedField;

        private List<string> assessmentLanguageField;

        private List<string> applicableRegionField;

        private List<string> assessmentTargetField;

        private List<string> assessmentJobCategoryField;

        private List<string> assessmentJobLevelField;

        /// <summary>
        /// AssessmentApplicabilityType class constructor
        /// </summary>
        public AssessmentApplicabilityType()
        {
            this.assessmentJobLevelField = new List<string>();
            this.assessmentJobCategoryField = new List<string>();
            this.assessmentTargetField = new List<string>();
            this.applicableRegionField = new List<string>();
            this.assessmentLanguageField = new List<string>();
            this.competencyAssessedField = new List<AssessmentCompetencyReferenceType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("CompetencyAssessed", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<AssessmentCompetencyReferenceType> CompetencyAssessed
        {
            get
            {
                return this.competencyAssessedField;
            }
            set
            {
                if ((this.competencyAssessedField != null))
                {
                    if ((competencyAssessedField.Equals(value) != true))
                    {
                        this.competencyAssessedField = value;
                        this.OnPropertyChanged("CompetencyAssessed");
                    }
                }
                else
                {
                    this.competencyAssessedField = value;
                    this.OnPropertyChanged("CompetencyAssessed");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AssessmentLanguage", DataType = "language", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> AssessmentLanguage
        {
            get
            {
                return this.assessmentLanguageField;
            }
            set
            {
                if ((this.assessmentLanguageField != null))
                {
                    if ((assessmentLanguageField.Equals(value) != true))
                    {
                        this.assessmentLanguageField = value;
                        this.OnPropertyChanged("AssessmentLanguage");
                    }
                }
                else
                {
                    this.assessmentLanguageField = value;
                    this.OnPropertyChanged("AssessmentLanguage");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ApplicableRegion", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> ApplicableRegion
        {
            get
            {
                return this.applicableRegionField;
            }
            set
            {
                if ((this.applicableRegionField != null))
                {
                    if ((applicableRegionField.Equals(value) != true))
                    {
                        this.applicableRegionField = value;
                        this.OnPropertyChanged("ApplicableRegion");
                    }
                }
                else
                {
                    this.applicableRegionField = value;
                    this.OnPropertyChanged("ApplicableRegion");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AssessmentTarget", Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> AssessmentTarget
        {
            get
            {
                return this.assessmentTargetField;
            }
            set
            {
                if ((this.assessmentTargetField != null))
                {
                    if ((assessmentTargetField.Equals(value) != true))
                    {
                        this.assessmentTargetField = value;
                        this.OnPropertyChanged("AssessmentTarget");
                    }
                }
                else
                {
                    this.assessmentTargetField = value;
                    this.OnPropertyChanged("AssessmentTarget");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AssessmentJobCategory", Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> AssessmentJobCategory
        {
            get
            {
                return this.assessmentJobCategoryField;
            }
            set
            {
                if ((this.assessmentJobCategoryField != null))
                {
                    if ((assessmentJobCategoryField.Equals(value) != true))
                    {
                        this.assessmentJobCategoryField = value;
                        this.OnPropertyChanged("AssessmentJobCategory");
                    }
                }
                else
                {
                    this.assessmentJobCategoryField = value;
                    this.OnPropertyChanged("AssessmentJobCategory");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AssessmentJobLevel", Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> AssessmentJobLevel
        {
            get
            {
                return this.assessmentJobLevelField;
            }
            set
            {
                if ((this.assessmentJobLevelField != null))
                {
                    if ((assessmentJobLevelField.Equals(value) != true))
                    {
                        this.assessmentJobLevelField = value;
                        this.OnPropertyChanged("AssessmentJobLevel");
                    }
                }
                else
                {
                    this.assessmentJobLevelField = value;
                    this.OnPropertyChanged("AssessmentJobLevel");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentPackageReferenceType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentPackageReferenceType : EntityBase<AssessmentPackageReferenceType>
    {

        private EntityIdType packageIdField;

        private string nameField;

        private string descriptionField;

        private AdministrationInfoType administrationInfoField;

        private List<ResultInfoType> resultInfoField;

        /// <summary>
        /// AssessmentPackageReferenceType class constructor
        /// </summary>
        public AssessmentPackageReferenceType()
        {
            this.resultInfoField = new List<ResultInfoType>();
            this.administrationInfoField = new AdministrationInfoType();
            this.packageIdField = new EntityIdType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType PackageId
        {
            get
            {
                return this.packageIdField;
            }
            set
            {
                if ((this.packageIdField != null))
                {
                    if ((packageIdField.Equals(value) != true))
                    {
                        this.packageIdField = value;
                        this.OnPropertyChanged("PackageId");
                    }
                }
                else
                {
                    this.packageIdField = value;
                    this.OnPropertyChanged("PackageId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("Name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                if ((this.descriptionField != null))
                {
                    if ((descriptionField.Equals(value) != true))
                    {
                        this.descriptionField = value;
                        this.OnPropertyChanged("Description");
                    }
                }
                else
                {
                    this.descriptionField = value;
                    this.OnPropertyChanged("Description");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdministrationInfoType AdministrationInfo
        {
            get
            {
                return this.administrationInfoField;
            }
            set
            {
                if ((this.administrationInfoField != null))
                {
                    if ((administrationInfoField.Equals(value) != true))
                    {
                        this.administrationInfoField = value;
                        this.OnPropertyChanged("AdministrationInfo");
                    }
                }
                else
                {
                    this.administrationInfoField = value;
                    this.OnPropertyChanged("AdministrationInfo");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ResultInfo", Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ResultInfoType> ResultInfo
        {
            get
            {
                return this.resultInfoField;
            }
            set
            {
                if ((this.resultInfoField != null))
                {
                    if ((resultInfoField.Equals(value) != true))
                    {
                        this.resultInfoField = value;
                        this.OnPropertyChanged("ResultInfo");
                    }
                }
                else
                {
                    this.resultInfoField = value;
                    this.OnPropertyChanged("ResultInfo");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentSubjectType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentSubjectType : EntityBase<AssessmentSubjectType>
    {

        private EntityIdType subjectIdField;

        private PersonNameType personNameField;

        private List<ContactMethodType> contactMethodField;

        private AssessmentPersonDescriptorsType assessmentPersonDescriptorsField;

        /// <summary>
        /// AssessmentSubjectType class constructor
        /// </summary>
        public AssessmentSubjectType()
        {
            this.assessmentPersonDescriptorsField = new AssessmentPersonDescriptorsType();
            this.contactMethodField = new List<ContactMethodType>();
            this.personNameField = new PersonNameType();
            this.subjectIdField = new EntityIdType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType SubjectId
        {
            get
            {
                return this.subjectIdField;
            }
            set
            {
                if ((this.subjectIdField != null))
                {
                    if ((subjectIdField.Equals(value) != true))
                    {
                        this.subjectIdField = value;
                        this.OnPropertyChanged("SubjectId");
                    }
                }
                else
                {
                    this.subjectIdField = value;
                    this.OnPropertyChanged("SubjectId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersonNameType PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                if ((this.personNameField != null))
                {
                    if ((personNameField.Equals(value) != true))
                    {
                        this.personNameField = value;
                        this.OnPropertyChanged("PersonName");
                    }
                }
                else
                {
                    this.personNameField = value;
                    this.OnPropertyChanged("PersonName");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ContactMethod", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ContactMethodType> ContactMethod
        {
            get
            {
                return this.contactMethodField;
            }
            set
            {
                if ((this.contactMethodField != null))
                {
                    if ((contactMethodField.Equals(value) != true))
                    {
                        this.contactMethodField = value;
                        this.OnPropertyChanged("ContactMethod");
                    }
                }
                else
                {
                    this.contactMethodField = value;
                    this.OnPropertyChanged("ContactMethod");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssessmentPersonDescriptorsType AssessmentPersonDescriptors
        {
            get
            {
                return this.assessmentPersonDescriptorsField;
            }
            set
            {
                if ((this.assessmentPersonDescriptorsField != null))
                {
                    if ((assessmentPersonDescriptorsField.Equals(value) != true))
                    {
                        this.assessmentPersonDescriptorsField = value;
                        this.OnPropertyChanged("AssessmentPersonDescriptors");
                    }
                }
                else
                {
                    this.assessmentPersonDescriptorsField = value;
                    this.OnPropertyChanged("AssessmentPersonDescriptors");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentPersonDescriptorsType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentPersonDescriptorsType : EntityBase<AssessmentPersonDescriptorsType>
    {

        private AssessmentLegalIdentifiersType legalIdentifiersField;

        private AssessmentDemographicDescriptorsType demographicDescriptorsField;

        private AssessmentBiologicalDescriptorsType biologicalDescriptorsField;

        private UserAreaType userAreaField;

        /// <summary>
        /// AssessmentPersonDescriptorsType class constructor
        /// </summary>
        public AssessmentPersonDescriptorsType()
        {
            this.userAreaField = new UserAreaType();
            this.biologicalDescriptorsField = new AssessmentBiologicalDescriptorsType();
            this.demographicDescriptorsField = new AssessmentDemographicDescriptorsType();
            this.legalIdentifiersField = new AssessmentLegalIdentifiersType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssessmentLegalIdentifiersType LegalIdentifiers
        {
            get
            {
                return this.legalIdentifiersField;
            }
            set
            {
                if ((this.legalIdentifiersField != null))
                {
                    if ((legalIdentifiersField.Equals(value) != true))
                    {
                        this.legalIdentifiersField = value;
                        this.OnPropertyChanged("LegalIdentifiers");
                    }
                }
                else
                {
                    this.legalIdentifiersField = value;
                    this.OnPropertyChanged("LegalIdentifiers");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssessmentDemographicDescriptorsType DemographicDescriptors
        {
            get
            {
                return this.demographicDescriptorsField;
            }
            set
            {
                if ((this.demographicDescriptorsField != null))
                {
                    if ((demographicDescriptorsField.Equals(value) != true))
                    {
                        this.demographicDescriptorsField = value;
                        this.OnPropertyChanged("DemographicDescriptors");
                    }
                }
                else
                {
                    this.demographicDescriptorsField = value;
                    this.OnPropertyChanged("DemographicDescriptors");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssessmentBiologicalDescriptorsType BiologicalDescriptors
        {
            get
            {
                return this.biologicalDescriptorsField;
            }
            set
            {
                if ((this.biologicalDescriptorsField != null))
                {
                    if ((biologicalDescriptorsField.Equals(value) != true))
                    {
                        this.biologicalDescriptorsField = value;
                        this.OnPropertyChanged("BiologicalDescriptors");
                    }
                }
                else
                {
                    this.biologicalDescriptorsField = value;
                    this.OnPropertyChanged("BiologicalDescriptors");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAreaType UserArea
        {
            get
            {
                return this.userAreaField;
            }
            set
            {
                if ((this.userAreaField != null))
                {
                    if ((userAreaField.Equals(value) != true))
                    {
                        this.userAreaField = value;
                        this.OnPropertyChanged("UserArea");
                    }
                }
                else
                {
                    this.userAreaField = value;
                    this.OnPropertyChanged("UserArea");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentLegalIdentifiersType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentLegalIdentifiersType : EntityBase<AssessmentLegalIdentifiersType>
    {

        private List<PersonLegalIdType> personLegalIdField;

        private List<AssessmentLegalIdentifiersTypeMilitaryStatus> militaryStatusField;

        /// <summary>
        /// AssessmentLegalIdentifiersType class constructor
        /// </summary>
        public AssessmentLegalIdentifiersType()
        {
            this.militaryStatusField = new List<AssessmentLegalIdentifiersTypeMilitaryStatus>();
            this.personLegalIdField = new List<PersonLegalIdType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("PersonLegalId", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<PersonLegalIdType> PersonLegalId
        {
            get
            {
                return this.personLegalIdField;
            }
            set
            {
                if ((this.personLegalIdField != null))
                {
                    if ((personLegalIdField.Equals(value) != true))
                    {
                        this.personLegalIdField = value;
                        this.OnPropertyChanged("PersonLegalId");
                    }
                }
                else
                {
                    this.personLegalIdField = value;
                    this.OnPropertyChanged("PersonLegalId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("MilitaryStatus", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<AssessmentLegalIdentifiersTypeMilitaryStatus> MilitaryStatus
        {
            get
            {
                return this.militaryStatusField;
            }
            set
            {
                if ((this.militaryStatusField != null))
                {
                    if ((militaryStatusField.Equals(value) != true))
                    {
                        this.militaryStatusField = value;
                        this.OnPropertyChanged("MilitaryStatus");
                    }
                }
                else
                {
                    this.militaryStatusField = value;
                    this.OnPropertyChanged("MilitaryStatus");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentLegalIdentifiersTypeMilitaryStatus", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentLegalIdentifiersTypeMilitaryStatus : EntityBase<AssessmentLegalIdentifiersTypeMilitaryStatus>
    {

        private string typeField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                if ((this.typeField != null))
                {
                    if ((typeField.Equals(value) != true))
                    {
                        this.typeField = value;
                        this.OnPropertyChanged("type");
                    }
                }
                else
                {
                    this.typeField = value;
                    this.OnPropertyChanged("type");
                }
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((this.valueField != null))
                {
                    if ((valueField.Equals(value) != true))
                    {
                        this.valueField = value;
                        this.OnPropertyChanged("Value");
                    }
                }
                else
                {
                    this.valueField = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentDemographicDescriptorsType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentDemographicDescriptorsType : EntityBase<AssessmentDemographicDescriptorsType>
    {

        private List<string> raceField;

        private List<string> ethnicityField;

        private List<string> nationalityField;

        private List<string> primaryLanguageField;

        /// <summary>
        /// AssessmentDemographicDescriptorsType class constructor
        /// </summary>
        public AssessmentDemographicDescriptorsType()
        {
            this.primaryLanguageField = new List<string>();
            this.nationalityField = new List<string>();
            this.ethnicityField = new List<string>();
            this.raceField = new List<string>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Race", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Race
        {
            get
            {
                return this.raceField;
            }
            set
            {
                if ((this.raceField != null))
                {
                    if ((raceField.Equals(value) != true))
                    {
                        this.raceField = value;
                        this.OnPropertyChanged("Race");
                    }
                }
                else
                {
                    this.raceField = value;
                    this.OnPropertyChanged("Race");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Ethnicity", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Ethnicity
        {
            get
            {
                return this.ethnicityField;
            }
            set
            {
                if ((this.ethnicityField != null))
                {
                    if ((ethnicityField.Equals(value) != true))
                    {
                        this.ethnicityField = value;
                        this.OnPropertyChanged("Ethnicity");
                    }
                }
                else
                {
                    this.ethnicityField = value;
                    this.OnPropertyChanged("Ethnicity");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Nationality", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                if ((this.nationalityField != null))
                {
                    if ((nationalityField.Equals(value) != true))
                    {
                        this.nationalityField = value;
                        this.OnPropertyChanged("Nationality");
                    }
                }
                else
                {
                    this.nationalityField = value;
                    this.OnPropertyChanged("Nationality");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("PrimaryLanguage", DataType = "language", Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> PrimaryLanguage
        {
            get
            {
                return this.primaryLanguageField;
            }
            set
            {
                if ((this.primaryLanguageField != null))
                {
                    if ((primaryLanguageField.Equals(value) != true))
                    {
                        this.primaryLanguageField = value;
                        this.OnPropertyChanged("PrimaryLanguage");
                    }
                }
                else
                {
                    this.primaryLanguageField = value;
                    this.OnPropertyChanged("PrimaryLanguage");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentBiologicalDescriptorsType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentBiologicalDescriptorsType : EntityBase<AssessmentBiologicalDescriptorsType>
    {

        private object itemField;

        private AssessmentBiologicalDescriptorsTypeAge ageField;

        private string genderCodeField;

        private List<DisabilityInfoType> disabilityInfoField;

        /// <summary>
        /// AssessmentBiologicalDescriptorsType class constructor
        /// </summary>
        public AssessmentBiologicalDescriptorsType()
        {
            this.disabilityInfoField = new List<DisabilityInfoType>();
            this.ageField = new AssessmentBiologicalDescriptorsTypeAge();
        }

        [System.Xml.Serialization.XmlElementAttribute("DateOfBirth", typeof(System.DateTime), DataType = "date", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("MonthDayOfBirth", typeof(string), DataType = "gMonthDay", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                if ((this.itemField != null))
                {
                    if ((itemField.Equals(value) != true))
                    {
                        this.itemField = value;
                        this.OnPropertyChanged("Item");
                    }
                }
                else
                {
                    this.itemField = value;
                    this.OnPropertyChanged("Item");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssessmentBiologicalDescriptorsTypeAge Age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                if ((this.ageField != null))
                {
                    if ((ageField.Equals(value) != true))
                    {
                        this.ageField = value;
                        this.OnPropertyChanged("Age");
                    }
                }
                else
                {
                    this.ageField = value;
                    this.OnPropertyChanged("Age");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenderCode
        {
            get
            {
                return this.genderCodeField;
            }
            set
            {
                if ((this.genderCodeField != null))
                {
                    if ((genderCodeField.Equals(value) != true))
                    {
                        this.genderCodeField = value;
                        this.OnPropertyChanged("GenderCode");
                    }
                }
                else
                {
                    this.genderCodeField = value;
                    this.OnPropertyChanged("GenderCode");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DisabilityInfo", Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<DisabilityInfoType> DisabilityInfo
        {
            get
            {
                return this.disabilityInfoField;
            }
            set
            {
                if ((this.disabilityInfoField != null))
                {
                    if ((disabilityInfoField.Equals(value) != true))
                    {
                        this.disabilityInfoField = value;
                        this.OnPropertyChanged("DisabilityInfo");
                    }
                }
                else
                {
                    this.disabilityInfoField = value;
                    this.OnPropertyChanged("DisabilityInfo");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssessmentBiologicalDescriptorsTypeAge", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssessmentBiologicalDescriptorsTypeAge : EntityBase<AssessmentBiologicalDescriptorsTypeAge>
    {

        private object itemField;

        [System.Xml.Serialization.XmlElementAttribute("AgeBand", typeof(object), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("AgeNumeric", typeof(string), DataType = "nonNegativeInteger", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                if ((this.itemField != null))
                {
                    if ((itemField.Equals(value) != true))
                    {
                        this.itemField = value;
                        this.OnPropertyChanged("Item");
                    }
                }
                else
                {
                    this.itemField = value;
                    this.OnPropertyChanged("Item");
                }
            }
        }
    }
}
