// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.0.0.19662
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute("Assignment", Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssignmentType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssignmentType : EntityBase<AssignmentType>
    {

        private List<EntityIdType> assignmentIdField;

        private AssignmentTypeReferenceInformation referenceInformationField;

        private CustomerReportingRequirementsType customerReportingRequirementsField;

        private List<RatesType> ratesField;

        private List<StaffingShiftType> staffingShiftField;

        private AssignmentTypeAssignmentDateRange assignmentDateRangeField;

        private string endReasonCommentsField;

        private List<AssignmentTypeContractInformation> contractInformationField;

        private UserAreaType userAreaField;

        private string assignmentStatusField;

        private string langField;

        [System.Xml.Serialization.XmlElementAttribute("AssignmentId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> AssignmentId
        {
            get
            {
                if ((this.assignmentIdField == null))
                {
                    this.assignmentIdField = new List<EntityIdType>();
                }
                return this.assignmentIdField;
            }
            set
            {
                if ((this.assignmentIdField != null))
                {
                    if ((assignmentIdField.Equals(value) != true))
                    {
                        this.assignmentIdField = value;
                        this.OnPropertyChanged("AssignmentId");
                    }
                }
                else
                {
                    this.assignmentIdField = value;
                    this.OnPropertyChanged("AssignmentId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssignmentTypeReferenceInformation ReferenceInformation
        {
            get
            {
                return this.referenceInformationField;
            }
            set
            {
                if ((this.referenceInformationField != null))
                {
                    if ((referenceInformationField.Equals(value) != true))
                    {
                        this.referenceInformationField = value;
                        this.OnPropertyChanged("ReferenceInformation");
                    }
                }
                else
                {
                    this.referenceInformationField = value;
                    this.OnPropertyChanged("ReferenceInformation");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerReportingRequirementsType CustomerReportingRequirements
        {
            get
            {
                return this.customerReportingRequirementsField;
            }
            set
            {
                if ((this.customerReportingRequirementsField != null))
                {
                    if ((customerReportingRequirementsField.Equals(value) != true))
                    {
                        this.customerReportingRequirementsField = value;
                        this.OnPropertyChanged("CustomerReportingRequirements");
                    }
                }
                else
                {
                    this.customerReportingRequirementsField = value;
                    this.OnPropertyChanged("CustomerReportingRequirements");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Rates")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<RatesType> Rates
        {
            get
            {
                if ((this.ratesField == null))
                {
                    this.ratesField = new List<RatesType>();
                }
                return this.ratesField;
            }
            set
            {
                if ((this.ratesField != null))
                {
                    if ((ratesField.Equals(value) != true))
                    {
                        this.ratesField = value;
                        this.OnPropertyChanged("Rates");
                    }
                }
                else
                {
                    this.ratesField = value;
                    this.OnPropertyChanged("Rates");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("StaffingShift")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<StaffingShiftType> StaffingShift
        {
            get
            {
                if ((this.staffingShiftField == null))
                {
                    this.staffingShiftField = new List<StaffingShiftType>();
                }
                return this.staffingShiftField;
            }
            set
            {
                if ((this.staffingShiftField != null))
                {
                    if ((staffingShiftField.Equals(value) != true))
                    {
                        this.staffingShiftField = value;
                        this.OnPropertyChanged("StaffingShift");
                    }
                }
                else
                {
                    this.staffingShiftField = value;
                    this.OnPropertyChanged("StaffingShift");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AssignmentTypeAssignmentDateRange AssignmentDateRange
        {
            get
            {
                return this.assignmentDateRangeField;
            }
            set
            {
                if ((this.assignmentDateRangeField != null))
                {
                    if ((assignmentDateRangeField.Equals(value) != true))
                    {
                        this.assignmentDateRangeField = value;
                        this.OnPropertyChanged("AssignmentDateRange");
                    }
                }
                else
                {
                    this.assignmentDateRangeField = value;
                    this.OnPropertyChanged("AssignmentDateRange");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndReasonComments
        {
            get
            {
                return this.endReasonCommentsField;
            }
            set
            {
                if ((this.endReasonCommentsField != null))
                {
                    if ((endReasonCommentsField.Equals(value) != true))
                    {
                        this.endReasonCommentsField = value;
                        this.OnPropertyChanged("EndReasonComments");
                    }
                }
                else
                {
                    this.endReasonCommentsField = value;
                    this.OnPropertyChanged("EndReasonComments");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ContractInformation")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<AssignmentTypeContractInformation> ContractInformation
        {
            get
            {
                if ((this.contractInformationField == null))
                {
                    this.contractInformationField = new List<AssignmentTypeContractInformation>();
                }
                return this.contractInformationField;
            }
            set
            {
                if ((this.contractInformationField != null))
                {
                    if ((contractInformationField.Equals(value) != true))
                    {
                        this.contractInformationField = value;
                        this.OnPropertyChanged("ContractInformation");
                    }
                }
                else
                {
                    this.contractInformationField = value;
                    this.OnPropertyChanged("ContractInformation");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAreaType UserArea
        {
            get
            {
                return this.userAreaField;
            }
            set
            {
                if ((this.userAreaField != null))
                {
                    if ((userAreaField.Equals(value) != true))
                    {
                        this.userAreaField = value;
                        this.OnPropertyChanged("UserArea");
                    }
                }
                else
                {
                    this.userAreaField = value;
                    this.OnPropertyChanged("UserArea");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string assignmentStatus
        {
            get
            {
                return this.assignmentStatusField;
            }
            set
            {
                if ((this.assignmentStatusField != null))
                {
                    if ((assignmentStatusField.Equals(value) != true))
                    {
                        this.assignmentStatusField = value;
                        this.OnPropertyChanged("assignmentStatus");
                    }
                }
                else
                {
                    this.assignmentStatusField = value;
                    this.OnPropertyChanged("assignmentStatus");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                if ((this.langField != null))
                {
                    if ((langField.Equals(value) != true))
                    {
                        this.langField = value;
                        this.OnPropertyChanged("lang");
                    }
                }
                else
                {
                    this.langField = value;
                    this.OnPropertyChanged("lang");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum KnownAssignmentStatus
    {
        [System.Xml.Serialization.XmlEnumAttribute("active")]
        Active,
        [System.Xml.Serialization.XmlEnumAttribute("inactive")]
        Inactive,
        [System.Xml.Serialization.XmlEnumAttribute("suspended")]
        Suspended,
        [System.Xml.Serialization.XmlEnumAttribute("pending")]
        Pending,
        [System.Xml.Serialization.XmlEnumAttribute("revised")]
        Revised,
        [System.Xml.Serialization.XmlEnumAttribute("cancelled")]
        Cancelled,
        [System.Xml.Serialization.XmlEnumAttribute("ended")]
        Ended
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssignmentTypeReferenceInformation", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssignmentTypeReferenceInformation : EntityBase<AssignmentTypeReferenceInformation>
    {

        private List<EntityIdType> staffingCustomerIdField;

        private List<EntityIdType> staffingCustomerOrgUnitIdField;

        private List<EntityIdType> orderIdField;

        private List<EntityIdType> humanResourceIdField;

        private List<EntityIdType> intermediaryIdField;

        private List<EntityIdType> positionIdField;

        private List<EntityIdType> staffingSupplierIdField;

        private List<EntityIdType> billToEntityIdField;

        private List<EntityIdType> staffingSupplierOrgUnitIdField;

        private List<EntityIdType> masterOrderIdField;

        private List<EntityIdType> timeCardIdField;

        private List<EntityIdType> invoiceIdField;

        private List<EntityIdType> staffingOrganizationIdField;

        private UserAreaType userAreaField;

        [System.Xml.Serialization.XmlElementAttribute("StaffingCustomerId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> StaffingCustomerId
        {
            get
            {
                if ((this.staffingCustomerIdField == null))
                {
                    this.staffingCustomerIdField = new List<EntityIdType>();
                }
                return this.staffingCustomerIdField;
            }
            set
            {
                if ((this.staffingCustomerIdField != null))
                {
                    if ((staffingCustomerIdField.Equals(value) != true))
                    {
                        this.staffingCustomerIdField = value;
                        this.OnPropertyChanged("StaffingCustomerId");
                    }
                }
                else
                {
                    this.staffingCustomerIdField = value;
                    this.OnPropertyChanged("StaffingCustomerId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("StaffingCustomerOrgUnitId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> StaffingCustomerOrgUnitId
        {
            get
            {
                if ((this.staffingCustomerOrgUnitIdField == null))
                {
                    this.staffingCustomerOrgUnitIdField = new List<EntityIdType>();
                }
                return this.staffingCustomerOrgUnitIdField;
            }
            set
            {
                if ((this.staffingCustomerOrgUnitIdField != null))
                {
                    if ((staffingCustomerOrgUnitIdField.Equals(value) != true))
                    {
                        this.staffingCustomerOrgUnitIdField = value;
                        this.OnPropertyChanged("StaffingCustomerOrgUnitId");
                    }
                }
                else
                {
                    this.staffingCustomerOrgUnitIdField = value;
                    this.OnPropertyChanged("StaffingCustomerOrgUnitId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("OrderId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> OrderId
        {
            get
            {
                if ((this.orderIdField == null))
                {
                    this.orderIdField = new List<EntityIdType>();
                }
                return this.orderIdField;
            }
            set
            {
                if ((this.orderIdField != null))
                {
                    if ((orderIdField.Equals(value) != true))
                    {
                        this.orderIdField = value;
                        this.OnPropertyChanged("OrderId");
                    }
                }
                else
                {
                    this.orderIdField = value;
                    this.OnPropertyChanged("OrderId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("HumanResourceId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> HumanResourceId
        {
            get
            {
                if ((this.humanResourceIdField == null))
                {
                    this.humanResourceIdField = new List<EntityIdType>();
                }
                return this.humanResourceIdField;
            }
            set
            {
                if ((this.humanResourceIdField != null))
                {
                    if ((humanResourceIdField.Equals(value) != true))
                    {
                        this.humanResourceIdField = value;
                        this.OnPropertyChanged("HumanResourceId");
                    }
                }
                else
                {
                    this.humanResourceIdField = value;
                    this.OnPropertyChanged("HumanResourceId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("IntermediaryId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> IntermediaryId
        {
            get
            {
                if ((this.intermediaryIdField == null))
                {
                    this.intermediaryIdField = new List<EntityIdType>();
                }
                return this.intermediaryIdField;
            }
            set
            {
                if ((this.intermediaryIdField != null))
                {
                    if ((intermediaryIdField.Equals(value) != true))
                    {
                        this.intermediaryIdField = value;
                        this.OnPropertyChanged("IntermediaryId");
                    }
                }
                else
                {
                    this.intermediaryIdField = value;
                    this.OnPropertyChanged("IntermediaryId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("PositionId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> PositionId
        {
            get
            {
                if ((this.positionIdField == null))
                {
                    this.positionIdField = new List<EntityIdType>();
                }
                return this.positionIdField;
            }
            set
            {
                if ((this.positionIdField != null))
                {
                    if ((positionIdField.Equals(value) != true))
                    {
                        this.positionIdField = value;
                        this.OnPropertyChanged("PositionId");
                    }
                }
                else
                {
                    this.positionIdField = value;
                    this.OnPropertyChanged("PositionId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("StaffingSupplierId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> StaffingSupplierId
        {
            get
            {
                if ((this.staffingSupplierIdField == null))
                {
                    this.staffingSupplierIdField = new List<EntityIdType>();
                }
                return this.staffingSupplierIdField;
            }
            set
            {
                if ((this.staffingSupplierIdField != null))
                {
                    if ((staffingSupplierIdField.Equals(value) != true))
                    {
                        this.staffingSupplierIdField = value;
                        this.OnPropertyChanged("StaffingSupplierId");
                    }
                }
                else
                {
                    this.staffingSupplierIdField = value;
                    this.OnPropertyChanged("StaffingSupplierId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("BillToEntityId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> BillToEntityId
        {
            get
            {
                if ((this.billToEntityIdField == null))
                {
                    this.billToEntityIdField = new List<EntityIdType>();
                }
                return this.billToEntityIdField;
            }
            set
            {
                if ((this.billToEntityIdField != null))
                {
                    if ((billToEntityIdField.Equals(value) != true))
                    {
                        this.billToEntityIdField = value;
                        this.OnPropertyChanged("BillToEntityId");
                    }
                }
                else
                {
                    this.billToEntityIdField = value;
                    this.OnPropertyChanged("BillToEntityId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("StaffingSupplierOrgUnitId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> StaffingSupplierOrgUnitId
        {
            get
            {
                if ((this.staffingSupplierOrgUnitIdField == null))
                {
                    this.staffingSupplierOrgUnitIdField = new List<EntityIdType>();
                }
                return this.staffingSupplierOrgUnitIdField;
            }
            set
            {
                if ((this.staffingSupplierOrgUnitIdField != null))
                {
                    if ((staffingSupplierOrgUnitIdField.Equals(value) != true))
                    {
                        this.staffingSupplierOrgUnitIdField = value;
                        this.OnPropertyChanged("StaffingSupplierOrgUnitId");
                    }
                }
                else
                {
                    this.staffingSupplierOrgUnitIdField = value;
                    this.OnPropertyChanged("StaffingSupplierOrgUnitId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("MasterOrderId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> MasterOrderId
        {
            get
            {
                if ((this.masterOrderIdField == null))
                {
                    this.masterOrderIdField = new List<EntityIdType>();
                }
                return this.masterOrderIdField;
            }
            set
            {
                if ((this.masterOrderIdField != null))
                {
                    if ((masterOrderIdField.Equals(value) != true))
                    {
                        this.masterOrderIdField = value;
                        this.OnPropertyChanged("MasterOrderId");
                    }
                }
                else
                {
                    this.masterOrderIdField = value;
                    this.OnPropertyChanged("MasterOrderId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TimeCardId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> TimeCardId
        {
            get
            {
                if ((this.timeCardIdField == null))
                {
                    this.timeCardIdField = new List<EntityIdType>();
                }
                return this.timeCardIdField;
            }
            set
            {
                if ((this.timeCardIdField != null))
                {
                    if ((timeCardIdField.Equals(value) != true))
                    {
                        this.timeCardIdField = value;
                        this.OnPropertyChanged("TimeCardId");
                    }
                }
                else
                {
                    this.timeCardIdField = value;
                    this.OnPropertyChanged("TimeCardId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("InvoiceId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> InvoiceId
        {
            get
            {
                if ((this.invoiceIdField == null))
                {
                    this.invoiceIdField = new List<EntityIdType>();
                }
                return this.invoiceIdField;
            }
            set
            {
                if ((this.invoiceIdField != null))
                {
                    if ((invoiceIdField.Equals(value) != true))
                    {
                        this.invoiceIdField = value;
                        this.OnPropertyChanged("InvoiceId");
                    }
                }
                else
                {
                    this.invoiceIdField = value;
                    this.OnPropertyChanged("InvoiceId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("StaffingOrganizationId")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<EntityIdType> StaffingOrganizationId
        {
            get
            {
                if ((this.staffingOrganizationIdField == null))
                {
                    this.staffingOrganizationIdField = new List<EntityIdType>();
                }
                return this.staffingOrganizationIdField;
            }
            set
            {
                if ((this.staffingOrganizationIdField != null))
                {
                    if ((staffingOrganizationIdField.Equals(value) != true))
                    {
                        this.staffingOrganizationIdField = value;
                        this.OnPropertyChanged("StaffingOrganizationId");
                    }
                }
                else
                {
                    this.staffingOrganizationIdField = value;
                    this.OnPropertyChanged("StaffingOrganizationId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAreaType UserArea
        {
            get
            {
                return this.userAreaField;
            }
            set
            {
                if ((this.userAreaField != null))
                {
                    if ((userAreaField.Equals(value) != true))
                    {
                        this.userAreaField = value;
                        this.OnPropertyChanged("UserArea");
                    }
                }
                else
                {
                    this.userAreaField = value;
                    this.OnPropertyChanged("UserArea");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssignmentTypeAssignmentDateRange", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssignmentTypeAssignmentDateRange : EntityBase<AssignmentTypeAssignmentDateRange>
    {

        private string startDateField;

        private string expectedEndDateField;

        private string actualEndDateField;

        private string flexibilityMinDateField;

        private string flexibilityMaxDateField;

        private List<AssignmentTypeAssignmentDateRangeProbationaryPeriod> probationaryPeriodField;

        private List<AssignmentTypeAssignmentDateRangeSuspensionPeriod> suspensionPeriodField;

        private string effectiveDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                if ((this.startDateField != null))
                {
                    if ((startDateField.Equals(value) != true))
                    {
                        this.startDateField = value;
                        this.OnPropertyChanged("StartDate");
                    }
                }
                else
                {
                    this.startDateField = value;
                    this.OnPropertyChanged("StartDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpectedEndDate
        {
            get
            {
                return this.expectedEndDateField;
            }
            set
            {
                if ((this.expectedEndDateField != null))
                {
                    if ((expectedEndDateField.Equals(value) != true))
                    {
                        this.expectedEndDateField = value;
                        this.OnPropertyChanged("ExpectedEndDate");
                    }
                }
                else
                {
                    this.expectedEndDateField = value;
                    this.OnPropertyChanged("ExpectedEndDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActualEndDate
        {
            get
            {
                return this.actualEndDateField;
            }
            set
            {
                if ((this.actualEndDateField != null))
                {
                    if ((actualEndDateField.Equals(value) != true))
                    {
                        this.actualEndDateField = value;
                        this.OnPropertyChanged("ActualEndDate");
                    }
                }
                else
                {
                    this.actualEndDateField = value;
                    this.OnPropertyChanged("ActualEndDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexibilityMinDate
        {
            get
            {
                return this.flexibilityMinDateField;
            }
            set
            {
                if ((this.flexibilityMinDateField != null))
                {
                    if ((flexibilityMinDateField.Equals(value) != true))
                    {
                        this.flexibilityMinDateField = value;
                        this.OnPropertyChanged("FlexibilityMinDate");
                    }
                }
                else
                {
                    this.flexibilityMinDateField = value;
                    this.OnPropertyChanged("FlexibilityMinDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexibilityMaxDate
        {
            get
            {
                return this.flexibilityMaxDateField;
            }
            set
            {
                if ((this.flexibilityMaxDateField != null))
                {
                    if ((flexibilityMaxDateField.Equals(value) != true))
                    {
                        this.flexibilityMaxDateField = value;
                        this.OnPropertyChanged("FlexibilityMaxDate");
                    }
                }
                else
                {
                    this.flexibilityMaxDateField = value;
                    this.OnPropertyChanged("FlexibilityMaxDate");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ProbationaryPeriod")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<AssignmentTypeAssignmentDateRangeProbationaryPeriod> ProbationaryPeriod
        {
            get
            {
                if ((this.probationaryPeriodField == null))
                {
                    this.probationaryPeriodField = new List<AssignmentTypeAssignmentDateRangeProbationaryPeriod>();
                }
                return this.probationaryPeriodField;
            }
            set
            {
                if ((this.probationaryPeriodField != null))
                {
                    if ((probationaryPeriodField.Equals(value) != true))
                    {
                        this.probationaryPeriodField = value;
                        this.OnPropertyChanged("ProbationaryPeriod");
                    }
                }
                else
                {
                    this.probationaryPeriodField = value;
                    this.OnPropertyChanged("ProbationaryPeriod");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("SuspensionPeriod")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<AssignmentTypeAssignmentDateRangeSuspensionPeriod> SuspensionPeriod
        {
            get
            {
                if ((this.suspensionPeriodField == null))
                {
                    this.suspensionPeriodField = new List<AssignmentTypeAssignmentDateRangeSuspensionPeriod>();
                }
                return this.suspensionPeriodField;
            }
            set
            {
                if ((this.suspensionPeriodField != null))
                {
                    if ((suspensionPeriodField.Equals(value) != true))
                    {
                        this.suspensionPeriodField = value;
                        this.OnPropertyChanged("SuspensionPeriod");
                    }
                }
                else
                {
                    this.suspensionPeriodField = value;
                    this.OnPropertyChanged("SuspensionPeriod");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                if ((this.effectiveDateField != null))
                {
                    if ((effectiveDateField.Equals(value) != true))
                    {
                        this.effectiveDateField = value;
                        this.OnPropertyChanged("EffectiveDate");
                    }
                }
                else
                {
                    this.effectiveDateField = value;
                    this.OnPropertyChanged("EffectiveDate");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssignmentTypeAssignmentDateRangeProbationaryPeriod", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssignmentTypeAssignmentDateRangeProbationaryPeriod
    {

        private string unitOfMeasureField;

        private decimal valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitOfMeasure
        {
            get
            {
                return this.unitOfMeasureField;
            }
            set
            {
                if ((this.unitOfMeasureField != null))
                {
                    if ((unitOfMeasureField.Equals(value) != true))
                    {
                        this.unitOfMeasureField = value;
                    }
                }
                else
                {
                    this.unitOfMeasureField = value;
                }
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((valueField.Equals(value) != true))
                {
                    this.valueField = value;
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssignmentTypeAssignmentDateRangeSuspensionPeriod", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssignmentTypeAssignmentDateRangeSuspensionPeriod : EntityBase<AssignmentTypeAssignmentDateRangeSuspensionPeriod>
    {

        private string startDateField;

        private string endDateField;

        private string commentsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                if ((this.startDateField != null))
                {
                    if ((startDateField.Equals(value) != true))
                    {
                        this.startDateField = value;
                        this.OnPropertyChanged("StartDate");
                    }
                }
                else
                {
                    this.startDateField = value;
                    this.OnPropertyChanged("StartDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                if ((this.endDateField != null))
                {
                    if ((endDateField.Equals(value) != true))
                    {
                        this.endDateField = value;
                        this.OnPropertyChanged("EndDate");
                    }
                }
                else
                {
                    this.endDateField = value;
                    this.OnPropertyChanged("EndDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                if ((this.commentsField != null))
                {
                    if ((commentsField.Equals(value) != true))
                    {
                        this.commentsField = value;
                        this.OnPropertyChanged("Comments");
                    }
                }
                else
                {
                    this.commentsField = value;
                    this.OnPropertyChanged("Comments");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssignmentTypeContractInformation", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class AssignmentTypeContractInformation : EntityBase<AssignmentTypeContractInformation>
    {

        private EntityIdType contractIdField;

        private string legalInformationField;

        private string contractVersionField;

        private string contractVersionDateField;

        private string staffTypeField;

        private LocalContractRequirementsType localContractRequirementsField;

        private List<FrameAgreementType> frameAgreementInfoField;

        private string contractTypeField;

        private string contractStatusField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType ContractId
        {
            get
            {
                return this.contractIdField;
            }
            set
            {
                if ((this.contractIdField != null))
                {
                    if ((contractIdField.Equals(value) != true))
                    {
                        this.contractIdField = value;
                        this.OnPropertyChanged("ContractId");
                    }
                }
                else
                {
                    this.contractIdField = value;
                    this.OnPropertyChanged("ContractId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalInformation
        {
            get
            {
                return this.legalInformationField;
            }
            set
            {
                if ((this.legalInformationField != null))
                {
                    if ((legalInformationField.Equals(value) != true))
                    {
                        this.legalInformationField = value;
                        this.OnPropertyChanged("LegalInformation");
                    }
                }
                else
                {
                    this.legalInformationField = value;
                    this.OnPropertyChanged("LegalInformation");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractVersion
        {
            get
            {
                return this.contractVersionField;
            }
            set
            {
                if ((this.contractVersionField != null))
                {
                    if ((contractVersionField.Equals(value) != true))
                    {
                        this.contractVersionField = value;
                        this.OnPropertyChanged("ContractVersion");
                    }
                }
                else
                {
                    this.contractVersionField = value;
                    this.OnPropertyChanged("ContractVersion");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractVersionDate
        {
            get
            {
                return this.contractVersionDateField;
            }
            set
            {
                if ((this.contractVersionDateField != null))
                {
                    if ((contractVersionDateField.Equals(value) != true))
                    {
                        this.contractVersionDateField = value;
                        this.OnPropertyChanged("ContractVersionDate");
                    }
                }
                else
                {
                    this.contractVersionDateField = value;
                    this.OnPropertyChanged("ContractVersionDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffType
        {
            get
            {
                return this.staffTypeField;
            }
            set
            {
                if ((this.staffTypeField != null))
                {
                    if ((staffTypeField.Equals(value) != true))
                    {
                        this.staffTypeField = value;
                        this.OnPropertyChanged("StaffType");
                    }
                }
                else
                {
                    this.staffTypeField = value;
                    this.OnPropertyChanged("StaffType");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public LocalContractRequirementsType LocalContractRequirements
        {
            get
            {
                return this.localContractRequirementsField;
            }
            set
            {
                if ((this.localContractRequirementsField != null))
                {
                    if ((localContractRequirementsField.Equals(value) != true))
                    {
                        this.localContractRequirementsField = value;
                        this.OnPropertyChanged("LocalContractRequirements");
                    }
                }
                else
                {
                    this.localContractRequirementsField = value;
                    this.OnPropertyChanged("LocalContractRequirements");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("FrameAgreementInfo")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<FrameAgreementType> FrameAgreementInfo
        {
            get
            {
                if ((this.frameAgreementInfoField == null))
                {
                    this.frameAgreementInfoField = new List<FrameAgreementType>();
                }
                return this.frameAgreementInfoField;
            }
            set
            {
                if ((this.frameAgreementInfoField != null))
                {
                    if ((frameAgreementInfoField.Equals(value) != true))
                    {
                        this.frameAgreementInfoField = value;
                        this.OnPropertyChanged("FrameAgreementInfo");
                    }
                }
                else
                {
                    this.frameAgreementInfoField = value;
                    this.OnPropertyChanged("FrameAgreementInfo");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contractType
        {
            get
            {
                return this.contractTypeField;
            }
            set
            {
                if ((this.contractTypeField != null))
                {
                    if ((contractTypeField.Equals(value) != true))
                    {
                        this.contractTypeField = value;
                        this.OnPropertyChanged("contractType");
                    }
                }
                else
                {
                    this.contractTypeField = value;
                    this.OnPropertyChanged("contractType");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contractStatus
        {
            get
            {
                return this.contractStatusField;
            }
            set
            {
                if ((this.contractStatusField != null))
                {
                    if ((contractStatusField.Equals(value) != true))
                    {
                        this.contractStatusField = value;
                        this.OnPropertyChanged("contractStatus");
                    }
                }
                else
                {
                    this.contractStatusField = value;
                    this.OnPropertyChanged("contractStatus");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FrameAgreementType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class FrameAgreementType : EntityBase<FrameAgreementType>
    {

        private EntityIdType documentIdField;

        private string documentVersionField;

        private FrameAgreementTypeValidityDateRange validityDateRangeField;

        private string documentNameField;

        private string documentTypeField;

        private List<FrameAgreementTypeStaffingOrgContact> staffingOrgContactField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                if ((this.documentIdField != null))
                {
                    if ((documentIdField.Equals(value) != true))
                    {
                        this.documentIdField = value;
                        this.OnPropertyChanged("DocumentId");
                    }
                }
                else
                {
                    this.documentIdField = value;
                    this.OnPropertyChanged("DocumentId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentVersion
        {
            get
            {
                return this.documentVersionField;
            }
            set
            {
                if ((this.documentVersionField != null))
                {
                    if ((documentVersionField.Equals(value) != true))
                    {
                        this.documentVersionField = value;
                        this.OnPropertyChanged("DocumentVersion");
                    }
                }
                else
                {
                    this.documentVersionField = value;
                    this.OnPropertyChanged("DocumentVersion");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FrameAgreementTypeValidityDateRange ValidityDateRange
        {
            get
            {
                return this.validityDateRangeField;
            }
            set
            {
                if ((this.validityDateRangeField != null))
                {
                    if ((validityDateRangeField.Equals(value) != true))
                    {
                        this.validityDateRangeField = value;
                        this.OnPropertyChanged("ValidityDateRange");
                    }
                }
                else
                {
                    this.validityDateRangeField = value;
                    this.OnPropertyChanged("ValidityDateRange");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName
        {
            get
            {
                return this.documentNameField;
            }
            set
            {
                if ((this.documentNameField != null))
                {
                    if ((documentNameField.Equals(value) != true))
                    {
                        this.documentNameField = value;
                        this.OnPropertyChanged("DocumentName");
                    }
                }
                else
                {
                    this.documentNameField = value;
                    this.OnPropertyChanged("DocumentName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                if ((this.documentTypeField != null))
                {
                    if ((documentTypeField.Equals(value) != true))
                    {
                        this.documentTypeField = value;
                        this.OnPropertyChanged("DocumentType");
                    }
                }
                else
                {
                    this.documentTypeField = value;
                    this.OnPropertyChanged("DocumentType");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("StaffingOrgContact")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<FrameAgreementTypeStaffingOrgContact> StaffingOrgContact
        {
            get
            {
                if ((this.staffingOrgContactField == null))
                {
                    this.staffingOrgContactField = new List<FrameAgreementTypeStaffingOrgContact>();
                }
                return this.staffingOrgContactField;
            }
            set
            {
                if ((this.staffingOrgContactField != null))
                {
                    if ((staffingOrgContactField.Equals(value) != true))
                    {
                        this.staffingOrgContactField = value;
                        this.OnPropertyChanged("StaffingOrgContact");
                    }
                }
                else
                {
                    this.staffingOrgContactField = value;
                    this.OnPropertyChanged("StaffingOrgContact");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FrameAgreementTypeValidityDateRange", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class FrameAgreementTypeValidityDateRange : EntityBase<FrameAgreementTypeValidityDateRange>
    {

        private string startDateField;

        private string endDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                if ((this.startDateField != null))
                {
                    if ((startDateField.Equals(value) != true))
                    {
                        this.startDateField = value;
                        this.OnPropertyChanged("StartDate");
                    }
                }
                else
                {
                    this.startDateField = value;
                    this.OnPropertyChanged("StartDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                if ((this.endDateField != null))
                {
                    if ((endDateField.Equals(value) != true))
                    {
                        this.endDateField = value;
                        this.OnPropertyChanged("EndDate");
                    }
                }
                else
                {
                    this.endDateField = value;
                    this.OnPropertyChanged("EndDate");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FrameAgreementTypeStaffingOrgContact", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class FrameAgreementTypeStaffingOrgContact : ContactInfoType
    {

        private string typeOfOrganizationField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeOfOrganization
        {
            get
            {
                return this.typeOfOrganizationField;
            }
            set
            {
                if ((this.typeOfOrganizationField != null))
                {
                    if ((typeOfOrganizationField.Equals(value) != true))
                    {
                        this.typeOfOrganizationField = value;
                        this.OnPropertyChanged("typeOfOrganization");
                    }
                }
                else
                {
                    this.typeOfOrganizationField = value;
                    this.OnPropertyChanged("typeOfOrganization");
                }
            }
        }
    }
}
