// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.0.0.19662
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute("StaffingShift", Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "StaffingShiftType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class StaffingShiftType : EntityBase<StaffingShiftType>
    {

        private EntityIdType idField;

        private string nameField;

        private decimal hoursField;

        private bool hoursFieldSpecified;

        private string startTimeField;

        private string endTimeField;

        private string typeHoursField;

        private string commentField;

        private EntityIdType externalStaffingShiftSetIdField;

        private StaffingShiftTypeShiftPeriod shiftPeriodField;

        private bool shiftPeriodFieldSpecified;

        private string langField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField != null))
                {
                    if ((idField.Equals(value) != true))
                    {
                        this.idField = value;
                        this.OnPropertyChanged("Id");
                    }
                }
                else
                {
                    this.idField = value;
                    this.OnPropertyChanged("Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("Name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Hours
        {
            get
            {
                return this.hoursField;
            }
            set
            {
                if ((hoursField.Equals(value) != true))
                {
                    this.hoursField = value;
                    this.OnPropertyChanged("Hours");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HoursSpecified
        {
            get
            {
                return this.hoursFieldSpecified;
            }
            set
            {
                if ((hoursFieldSpecified.Equals(value) != true))
                {
                    this.hoursFieldSpecified = value;
                    this.OnPropertyChanged("HoursSpecified");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                if ((this.startTimeField != null))
                {
                    if ((startTimeField.Equals(value) != true))
                    {
                        this.startTimeField = value;
                        this.OnPropertyChanged("StartTime");
                    }
                }
                else
                {
                    this.startTimeField = value;
                    this.OnPropertyChanged("StartTime");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                if ((this.endTimeField != null))
                {
                    if ((endTimeField.Equals(value) != true))
                    {
                        this.endTimeField = value;
                        this.OnPropertyChanged("EndTime");
                    }
                }
                else
                {
                    this.endTimeField = value;
                    this.OnPropertyChanged("EndTime");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeHours
        {
            get
            {
                return this.typeHoursField;
            }
            set
            {
                if ((this.typeHoursField != null))
                {
                    if ((typeHoursField.Equals(value) != true))
                    {
                        this.typeHoursField = value;
                        this.OnPropertyChanged("TypeHours");
                    }
                }
                else
                {
                    this.typeHoursField = value;
                    this.OnPropertyChanged("TypeHours");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                if ((this.commentField != null))
                {
                    if ((commentField.Equals(value) != true))
                    {
                        this.commentField = value;
                        this.OnPropertyChanged("Comment");
                    }
                }
                else
                {
                    this.commentField = value;
                    this.OnPropertyChanged("Comment");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType ExternalStaffingShiftSetId
        {
            get
            {
                return this.externalStaffingShiftSetIdField;
            }
            set
            {
                if ((this.externalStaffingShiftSetIdField != null))
                {
                    if ((externalStaffingShiftSetIdField.Equals(value) != true))
                    {
                        this.externalStaffingShiftSetIdField = value;
                        this.OnPropertyChanged("ExternalStaffingShiftSetId");
                    }
                }
                else
                {
                    this.externalStaffingShiftSetIdField = value;
                    this.OnPropertyChanged("ExternalStaffingShiftSetId");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StaffingShiftTypeShiftPeriod shiftPeriod
        {
            get
            {
                return this.shiftPeriodField;
            }
            set
            {
                if ((shiftPeriodField.Equals(value) != true))
                {
                    this.shiftPeriodField = value;
                    this.OnPropertyChanged("shiftPeriod");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool shiftPeriodSpecified
        {
            get
            {
                return this.shiftPeriodFieldSpecified;
            }
            set
            {
                if ((shiftPeriodFieldSpecified.Equals(value) != true))
                {
                    this.shiftPeriodFieldSpecified = value;
                    this.OnPropertyChanged("shiftPeriodSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                if ((this.langField != null))
                {
                    if ((langField.Equals(value) != true))
                    {
                        this.langField = value;
                        this.OnPropertyChanged("lang");
                    }
                }
                else
                {
                    this.langField = value;
                    this.OnPropertyChanged("lang");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum StaffingShiftTypeShiftPeriod
    {

        /// <remarks/>
        monthly,

        /// <remarks/>
        weekly,

        /// <remarks/>
        daily,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,

        /// <remarks/>
        @event,
    }

}
