// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.33213
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.flex2go.nl/2015-12")]
    [System.Xml.Serialization.XmlRootAttribute("FlexGoHumanResource", Namespace = "http://www.flex2go.nl/2015-12", IsNullable = false)]
    public partial class FlexGoHumanResourceType : EntityBase<FlexGoHumanResourceType>
    {

        private int accountManagerIdField;

        private bool accountManagerIdFieldSpecified;

        private int afdelingIdField;

        private bool afdelingIdFieldSpecified;

        private int categorieIdField;

        private bool categorieIdFieldSpecified;

        private int bedrijfsCodeField;

        private bool bedrijfsCodeFieldSpecified;

        private int nummerField;

        private bool nummerFieldSpecified;

        private int organisatieIdField;

        private bool organisatieIdFieldSpecified;

        private int verzekeraarIdField;

        private bool verzekeraarIdFieldSpecified;

        private bool loonheffingKortingField;

        private bool loonheffingKortingFieldSpecified;

        private string functieField;

        private System.DateTime datumIndienstField;

        private bool datumIndienstFieldSpecified;

        private decimal verkoopTariefField;

        private bool verkoopTariefFieldSpecified;

        private decimal kostprijsField;

        private bool kostprijsFieldSpecified;

        private string faseField;

        private System.DateTime faseStartdatumField;

        private bool faseStartdatumFieldSpecified;

        private double faseWekenField;

        private bool faseWekenFieldSpecified;

        private List<FlexGoListType> linksField;

        private List<FlexGoNotitieType> notitiesField;

        public FlexGoHumanResourceType()
        {
            this.notitiesField = new List<FlexGoNotitieType>();
            this.linksField = new List<FlexGoListType>();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int AccountManagerId
        {
            get
            {
                return this.accountManagerIdField;
            }
            set
            {
                this.accountManagerIdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountManagerIdSpecified
        {
            get
            {
                return this.accountManagerIdFieldSpecified;
            }
            set
            {
                this.accountManagerIdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int AfdelingId
        {
            get
            {
                return this.afdelingIdField;
            }
            set
            {
                this.afdelingIdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfdelingIdSpecified
        {
            get
            {
                return this.afdelingIdFieldSpecified;
            }
            set
            {
                this.afdelingIdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int CategorieId
        {
            get
            {
                return this.categorieIdField;
            }
            set
            {
                this.categorieIdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategorieIdSpecified
        {
            get
            {
                return this.categorieIdFieldSpecified;
            }
            set
            {
                this.categorieIdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public int BedrijfsCode
        {
            get
            {
                return this.bedrijfsCodeField;
            }
            set
            {
                this.bedrijfsCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BedrijfsCodeSpecified
        {
            get
            {
                return this.bedrijfsCodeFieldSpecified;
            }
            set
            {
                this.bedrijfsCodeFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public int Nummer
        {
            get
            {
                return this.nummerField;
            }
            set
            {
                this.nummerField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NummerSpecified
        {
            get
            {
                return this.nummerFieldSpecified;
            }
            set
            {
                this.nummerFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public int OrganisatieId
        {
            get
            {
                return this.organisatieIdField;
            }
            set
            {
                this.organisatieIdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrganisatieIdSpecified
        {
            get
            {
                return this.organisatieIdFieldSpecified;
            }
            set
            {
                this.organisatieIdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public int VerzekeraarId
        {
            get
            {
                return this.verzekeraarIdField;
            }
            set
            {
                this.verzekeraarIdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerzekeraarIdSpecified
        {
            get
            {
                return this.verzekeraarIdFieldSpecified;
            }
            set
            {
                this.verzekeraarIdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public bool LoonheffingKorting
        {
            get
            {
                return this.loonheffingKortingField;
            }
            set
            {
                this.loonheffingKortingField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LoonheffingKortingSpecified
        {
            get
            {
                return this.loonheffingKortingFieldSpecified;
            }
            set
            {
                this.loonheffingKortingFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string Functie
        {
            get
            {
                return this.functieField;
            }
            set
            {
                this.functieField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public System.DateTime DatumIndienst
        {
            get
            {
                return this.datumIndienstField;
            }
            set
            {
                this.datumIndienstField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumIndienstSpecified
        {
            get
            {
                return this.datumIndienstFieldSpecified;
            }
            set
            {
                this.datumIndienstFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public decimal VerkoopTarief
        {
            get
            {
                return this.verkoopTariefField;
            }
            set
            {
                this.verkoopTariefField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerkoopTariefSpecified
        {
            get
            {
                return this.verkoopTariefFieldSpecified;
            }
            set
            {
                this.verkoopTariefFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public decimal Kostprijs
        {
            get
            {
                return this.kostprijsField;
            }
            set
            {
                this.kostprijsField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KostprijsSpecified
        {
            get
            {
                return this.kostprijsFieldSpecified;
            }
            set
            {
                this.kostprijsFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string Fase
        {
            get
            {
                return this.faseField;
            }
            set
            {
                this.faseField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public System.DateTime FaseStartdatum
        {
            get
            {
                return this.faseStartdatumField;
            }
            set
            {
                this.faseStartdatumField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FaseStartdatumSpecified
        {
            get
            {
                return this.faseStartdatumFieldSpecified;
            }
            set
            {
                this.faseStartdatumFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public double FaseWeken
        {
            get
            {
                return this.faseWekenField;
            }
            set
            {
                this.faseWekenField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FaseWekenSpecified
        {
            get
            {
                return this.faseWekenFieldSpecified;
            }
            set
            {
                this.faseWekenFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Links", Order = 15)]
        public List<FlexGoListType> Links
        {
            get
            {
                return this.linksField;
            }
            set
            {
                this.linksField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Notities", Order = 16)]
        public List<FlexGoNotitieType> Notities
        {
            get
            {
                return this.notitiesField;
            }
            set
            {
                this.notitiesField = value;
            }
        }
    }
}
