// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.33213
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flex2go.nl/2015-12")]
    [System.Xml.Serialization.XmlRootAttribute("FlexGoStaffingOrganization", Namespace="http://www.flex2go.nl/2015-12", IsNullable=false)]
    public partial class FlexGoStaffingOrganizationType : EntityBase<FlexGoStaffingOrganizationType> {
        
        private int accountManagerIdField;
        
        private bool accountManagerIdFieldSpecified;
        
        private int categorieIdField;
        
        private bool categorieIdFieldSpecified;
        
        private int bedrijfsCodeField;
        
        private bool bedrijfsCodeFieldSpecified;
        
        private int nummerField;
        
        private bool nummerFieldSpecified;
        
        private int bTWCodeField;
        
        private bool bTWCodeFieldSpecified;
        
        private int bTWTariefIdField;
        
        private bool bTWTariefIdFieldSpecified;
        
        private float kredietLimietField;
        
        private bool kredietLimietFieldSpecified;
        
        private decimal verkoopFactorField;
        
        private bool verkoopFactorFieldSpecified;
        
        private int betaalWijzeIdField;
        
        private bool betaalWijzeIdFieldSpecified;
        
        private int betaalTermijnIdField;
        
        private bool betaalTermijnIdFieldSpecified;
        
        private int betaalConditieIdField;
        
        private bool betaalConditieIdFieldSpecified;
        
        private int debiteurgroepIdField;
        
        private bool debiteurgroepIdFieldSpecified;
        
        private float gPercentageField;
        
        private bool gPercentageFieldSpecified;
        
        private string gPercentageRekeningField;
        
        private List<FlexGoListType> linksField;
        
        private List<FlexGoNotitieType> notitiesField;
        
        public FlexGoStaffingOrganizationType() {
            this.notitiesField = new List<FlexGoNotitieType>();
            this.linksField = new List<FlexGoListType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AccountManagerId {
            get {
                return this.accountManagerIdField;
            }
            set {
                this.accountManagerIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountManagerIdSpecified {
            get {
                return this.accountManagerIdFieldSpecified;
            }
            set {
                this.accountManagerIdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CategorieId {
            get {
                return this.categorieIdField;
            }
            set {
                this.categorieIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategorieIdSpecified {
            get {
                return this.categorieIdFieldSpecified;
            }
            set {
                this.categorieIdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int BedrijfsCode {
            get {
                return this.bedrijfsCodeField;
            }
            set {
                this.bedrijfsCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BedrijfsCodeSpecified {
            get {
                return this.bedrijfsCodeFieldSpecified;
            }
            set {
                this.bedrijfsCodeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Nummer {
            get {
                return this.nummerField;
            }
            set {
                this.nummerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NummerSpecified {
            get {
                return this.nummerFieldSpecified;
            }
            set {
                this.nummerFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int BTWCode {
            get {
                return this.bTWCodeField;
            }
            set {
                this.bTWCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BTWCodeSpecified {
            get {
                return this.bTWCodeFieldSpecified;
            }
            set {
                this.bTWCodeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int BTWTariefId {
            get {
                return this.bTWTariefIdField;
            }
            set {
                this.bTWTariefIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BTWTariefIdSpecified {
            get {
                return this.bTWTariefIdFieldSpecified;
            }
            set {
                this.bTWTariefIdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float KredietLimiet {
            get {
                return this.kredietLimietField;
            }
            set {
                this.kredietLimietField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KredietLimietSpecified {
            get {
                return this.kredietLimietFieldSpecified;
            }
            set {
                this.kredietLimietFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal VerkoopFactor {
            get {
                return this.verkoopFactorField;
            }
            set {
                this.verkoopFactorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerkoopFactorSpecified {
            get {
                return this.verkoopFactorFieldSpecified;
            }
            set {
                this.verkoopFactorFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int BetaalWijzeId {
            get {
                return this.betaalWijzeIdField;
            }
            set {
                this.betaalWijzeIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BetaalWijzeIdSpecified {
            get {
                return this.betaalWijzeIdFieldSpecified;
            }
            set {
                this.betaalWijzeIdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int BetaalTermijnId {
            get {
                return this.betaalTermijnIdField;
            }
            set {
                this.betaalTermijnIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BetaalTermijnIdSpecified {
            get {
                return this.betaalTermijnIdFieldSpecified;
            }
            set {
                this.betaalTermijnIdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int BetaalConditieId {
            get {
                return this.betaalConditieIdField;
            }
            set {
                this.betaalConditieIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BetaalConditieIdSpecified {
            get {
                return this.betaalConditieIdFieldSpecified;
            }
            set {
                this.betaalConditieIdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DebiteurgroepId {
            get {
                return this.debiteurgroepIdField;
            }
            set {
                this.debiteurgroepIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebiteurgroepIdSpecified {
            get {
                return this.debiteurgroepIdFieldSpecified;
            }
            set {
                this.debiteurgroepIdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public float GPercentage {
            get {
                return this.gPercentageField;
            }
            set {
                this.gPercentageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GPercentageSpecified {
            get {
                return this.gPercentageFieldSpecified;
            }
            set {
                this.gPercentageFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string GPercentageRekening {
            get {
                return this.gPercentageRekeningField;
            }
            set {
                this.gPercentageRekeningField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Links", Order=14)]
        public List<FlexGoListType> Links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Notities", Order=15)]
        public List<FlexGoNotitieType> Notities {
            get {
                return this.notitiesField;
            }
            set {
                this.notitiesField = value;
            }
        }
    }
}
