// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.33213
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.flex2go.nl/2012-04")]
    [System.Xml.Serialization.XmlRootAttribute("Flex2GoHumanResource", Namespace = "http://www.flex2go.nl/2012-04", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Flex2GoHumanResourceType", Namespace = "http://www.flex2go.nl/2012-04")]
    public partial class Flex2GoHumanResourceType : EntityBase<Flex2GoHumanResourceType>
    {

        private string phaseField;

        private string initialsField;

        private string nationalityField;

        private List<BankAccountInfoType> bankAccountInfoField;

        private List<BankAccountExtraType> bankAccountExtraField;

        private List<AvailablityType> availabilityField;

        private List<ReservationsType> reservationsField;

        private DriverLicenseType driverLicenseField;

        private string paymentPeriodField;

        private string placeOfBirthField;

        private string languageField;

        private string commentField;

        private string kindField;

        private string bureauIdField;

        private string bureauNaamField;

        private string relatieBeheerderIdField;

        private string managerField;

        private string countryOfBirthCodeField;

        private string statusField;

        private string maritalStatusField;

        private System.DateTime modifiedField;

        /// <summary>
        /// Flex2GoHumanResourceType class constructor
        /// </summary>
        public Flex2GoHumanResourceType()
        {
            this.driverLicenseField = new DriverLicenseType();
            this.reservationsField = new List<ReservationsType>();
            this.availabilityField = new List<AvailablityType>();
            this.bankAccountExtraField = new List<BankAccountExtraType>();
            this.bankAccountInfoField = new List<BankAccountInfoType>();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phase
        {
            get
            {
                return this.phaseField;
            }
            set
            {
                if ((this.phaseField != null))
                {
                    if ((phaseField.Equals(value) != true))
                    {
                        this.phaseField = value;
                        this.OnPropertyChanged("Phase");
                    }
                }
                else
                {
                    this.phaseField = value;
                    this.OnPropertyChanged("Phase");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Initials
        {
            get
            {
                return this.initialsField;
            }
            set
            {
                if ((this.initialsField != null))
                {
                    if ((initialsField.Equals(value) != true))
                    {
                        this.initialsField = value;
                        this.OnPropertyChanged("Initials");
                    }
                }
                else
                {
                    this.initialsField = value;
                    this.OnPropertyChanged("Initials");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                if ((this.nationalityField != null))
                {
                    if ((nationalityField.Equals(value) != true))
                    {
                        this.nationalityField = value;
                        this.OnPropertyChanged("Nationality");
                    }
                }
                else
                {
                    this.nationalityField = value;
                    this.OnPropertyChanged("Nationality");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("BankAccountInfo", Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<BankAccountInfoType> BankAccountInfo
        {
            get
            {
                return this.bankAccountInfoField;
            }
            set
            {
                if ((this.bankAccountInfoField != null))
                {
                    if ((bankAccountInfoField.Equals(value) != true))
                    {
                        this.bankAccountInfoField = value;
                        this.OnPropertyChanged("BankAccountInfo");
                    }
                }
                else
                {
                    this.bankAccountInfoField = value;
                    this.OnPropertyChanged("BankAccountInfo");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("BankAccountExtra", Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<BankAccountExtraType> BankAccountExtra
        {
            get
            {
                return this.bankAccountExtraField;
            }
            set
            {
                if ((this.bankAccountExtraField != null))
                {
                    if ((bankAccountExtraField.Equals(value) != true))
                    {
                        this.bankAccountExtraField = value;
                        this.OnPropertyChanged("BankAccountExtra");
                    }
                }
                else
                {
                    this.bankAccountExtraField = value;
                    this.OnPropertyChanged("BankAccountExtra");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Availability", Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<AvailablityType> Availability
        {
            get
            {
                return this.availabilityField;
            }
            set
            {
                if ((this.availabilityField != null))
                {
                    if ((availabilityField.Equals(value) != true))
                    {
                        this.availabilityField = value;
                        this.OnPropertyChanged("Availability");
                    }
                }
                else
                {
                    this.availabilityField = value;
                    this.OnPropertyChanged("Availability");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Reservations", Order = 6)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ReservationsType> Reservations
        {
            get
            {
                return this.reservationsField;
            }
            set
            {
                if ((this.reservationsField != null))
                {
                    if ((reservationsField.Equals(value) != true))
                    {
                        this.reservationsField = value;
                        this.OnPropertyChanged("Reservations");
                    }
                }
                else
                {
                    this.reservationsField = value;
                    this.OnPropertyChanged("Reservations");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DriverLicenseType DriverLicense
        {
            get
            {
                return this.driverLicenseField;
            }
            set
            {
                if ((this.driverLicenseField != null))
                {
                    if ((driverLicenseField.Equals(value) != true))
                    {
                        this.driverLicenseField = value;
                        this.OnPropertyChanged("DriverLicense");
                    }
                }
                else
                {
                    this.driverLicenseField = value;
                    this.OnPropertyChanged("DriverLicense");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentPeriod
        {
            get
            {
                return this.paymentPeriodField;
            }
            set
            {
                if ((this.paymentPeriodField != null))
                {
                    if ((paymentPeriodField.Equals(value) != true))
                    {
                        this.paymentPeriodField = value;
                        this.OnPropertyChanged("PaymentPeriod");
                    }
                }
                else
                {
                    this.paymentPeriodField = value;
                    this.OnPropertyChanged("PaymentPeriod");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceOfBirth
        {
            get
            {
                return this.placeOfBirthField;
            }
            set
            {
                if ((this.placeOfBirthField != null))
                {
                    if ((placeOfBirthField.Equals(value) != true))
                    {
                        this.placeOfBirthField = value;
                        this.OnPropertyChanged("PlaceOfBirth");
                    }
                }
                else
                {
                    this.placeOfBirthField = value;
                    this.OnPropertyChanged("PlaceOfBirth");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                if ((this.languageField != null))
                {
                    if ((languageField.Equals(value) != true))
                    {
                        this.languageField = value;
                        this.OnPropertyChanged("Language");
                    }
                }
                else
                {
                    this.languageField = value;
                    this.OnPropertyChanged("Language");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                if ((this.commentField != null))
                {
                    if ((commentField.Equals(value) != true))
                    {
                        this.commentField = value;
                        this.OnPropertyChanged("Comment");
                    }
                }
                else
                {
                    this.commentField = value;
                    this.OnPropertyChanged("Comment");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kind
        {
            get
            {
                return this.kindField;
            }
            set
            {
                if ((this.kindField != null))
                {
                    if ((kindField.Equals(value) != true))
                    {
                        this.kindField = value;
                        this.OnPropertyChanged("Kind");
                    }
                }
                else
                {
                    this.kindField = value;
                    this.OnPropertyChanged("Kind");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BureauId
        {
            get
            {
                return this.bureauIdField;
            }
            set
            {
                if ((this.bureauIdField != null))
                {
                    if ((bureauIdField.Equals(value) != true))
                    {
                        this.bureauIdField = value;
                        this.OnPropertyChanged("BureauId");
                    }
                }
                else
                {
                    this.bureauIdField = value;
                    this.OnPropertyChanged("BureauId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BureauNaam
        {
            get
            {
                return this.bureauNaamField;
            }
            set
            {
                if ((this.bureauNaamField != null))
                {
                    if ((bureauNaamField.Equals(value) != true))
                    {
                        this.bureauNaamField = value;
                        this.OnPropertyChanged("BureauNaam");
                    }
                }
                else
                {
                    this.bureauNaamField = value;
                    this.OnPropertyChanged("BureauNaam");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatieBeheerderId
        {
            get
            {
                return this.relatieBeheerderIdField;
            }
            set
            {
                if ((this.relatieBeheerderIdField != null))
                {
                    if ((relatieBeheerderIdField.Equals(value) != true))
                    {
                        this.relatieBeheerderIdField = value;
                        this.OnPropertyChanged("RelatieBeheerderId");
                    }
                }
                else
                {
                    this.relatieBeheerderIdField = value;
                    this.OnPropertyChanged("RelatieBeheerderId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manager
        {
            get
            {
                return this.managerField;
            }
            set
            {
                if ((this.managerField != null))
                {
                    if ((managerField.Equals(value) != true))
                    {
                        this.managerField = value;
                        this.OnPropertyChanged("Manager");
                    }
                }
                else
                {
                    this.managerField = value;
                    this.OnPropertyChanged("Manager");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryOfBirthCode
        {
            get
            {
                return this.countryOfBirthCodeField;
            }
            set
            {
                if ((this.countryOfBirthCodeField != null))
                {
                    if ((countryOfBirthCodeField.Equals(value) != true))
                    {
                        this.countryOfBirthCodeField = value;
                        this.OnPropertyChanged("CountryOfBirthCode");
                    }
                }
                else
                {
                    this.countryOfBirthCodeField = value;
                    this.OnPropertyChanged("CountryOfBirthCode");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                if ((this.statusField != null))
                {
                    if ((statusField.Equals(value) != true))
                    {
                        this.statusField = value;
                        this.OnPropertyChanged("Status");
                    }
                }
                else
                {
                    this.statusField = value;
                    this.OnPropertyChanged("Status");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus
        {
            get
            {
                return this.maritalStatusField;
            }
            set
            {
                if ((this.maritalStatusField != null))
                {
                    if ((maritalStatusField.Equals(value) != true))
                    {
                        this.maritalStatusField = value;
                        this.OnPropertyChanged("MaritalStatus");
                    }
                }
                else
                {
                    this.maritalStatusField = value;
                    this.OnPropertyChanged("MaritalStatus");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                if ((modifiedField.Equals(value) != true))
                {
                    this.modifiedField = value;
                    this.OnPropertyChanged("Modified");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.flex2go.nl/2012-04")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.flex2go.nl/2012-04", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DriverLicenseEndorsementsType", Namespace = "http://www.flex2go.nl/2012-04")]
    public partial class DriverLicenseEndorsementsType : EntityBase<DriverLicenseEndorsementsType>
    {

        private string nameField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("Name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.flex2go.nl/2012-04")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.flex2go.nl/2012-04", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DriverLicenseType", Namespace = "http://www.flex2go.nl/2012-04")]
    public partial class DriverLicenseType : EntityBase<DriverLicenseType>
    {

        private string numberField;

        private System.DateTime acuiredDateField;

        private bool acuiredDateFieldSpecified;

        private System.DateTime expireDateField;

        private bool expireDateFieldSpecified;

        private string countryField;

        private List<DriverLicenseEndorsementsType> endorsementsField;

        /// <summary>
        /// DriverLicenseType class constructor
        /// </summary>
        public DriverLicenseType()
        {
            this.endorsementsField = new List<DriverLicenseEndorsementsType>();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                if ((this.numberField != null))
                {
                    if ((numberField.Equals(value) != true))
                    {
                        this.numberField = value;
                        this.OnPropertyChanged("Number");
                    }
                }
                else
                {
                    this.numberField = value;
                    this.OnPropertyChanged("Number");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AcuiredDate
        {
            get
            {
                return this.acuiredDateField;
            }
            set
            {
                if ((acuiredDateField.Equals(value) != true))
                {
                    this.acuiredDateField = value;
                    this.OnPropertyChanged("AcuiredDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AcuiredDateSpecified
        {
            get
            {
                return this.acuiredDateFieldSpecified;
            }
            set
            {
                if ((acuiredDateFieldSpecified.Equals(value) != true))
                {
                    this.acuiredDateFieldSpecified = value;
                    this.OnPropertyChanged("AcuiredDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpireDate
        {
            get
            {
                return this.expireDateField;
            }
            set
            {
                if ((expireDateField.Equals(value) != true))
                {
                    this.expireDateField = value;
                    this.OnPropertyChanged("ExpireDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExpireDateSpecified
        {
            get
            {
                return this.expireDateFieldSpecified;
            }
            set
            {
                if ((expireDateFieldSpecified.Equals(value) != true))
                {
                    this.expireDateFieldSpecified = value;
                    this.OnPropertyChanged("ExpireDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                if ((this.countryField != null))
                {
                    if ((countryField.Equals(value) != true))
                    {
                        this.countryField = value;
                        this.OnPropertyChanged("Country");
                    }
                }
                else
                {
                    this.countryField = value;
                    this.OnPropertyChanged("Country");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Endorsements", Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<DriverLicenseEndorsementsType> Endorsements
        {
            get
            {
                return this.endorsementsField;
            }
            set
            {
                if ((this.endorsementsField != null))
                {
                    if ((endorsementsField.Equals(value) != true))
                    {
                        this.endorsementsField = value;
                        this.OnPropertyChanged("Endorsements");
                    }
                }
                else
                {
                    this.endorsementsField = value;
                    this.OnPropertyChanged("Endorsements");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.flex2go.nl/2012-04")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.flex2go.nl/2012-04", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ReservationsType", Namespace = "http://www.flex2go.nl/2012-04")]
    public partial class ReservationsType : EntityBase<ReservationsType>
    {

        private int yearField;

        private bool yearFieldSpecified;

        private string nameField;

        private decimal amountField;

        private bool amountFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                if ((yearField.Equals(value) != true))
                {
                    this.yearField = value;
                    this.OnPropertyChanged("Year");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool YearSpecified
        {
            get
            {
                return this.yearFieldSpecified;
            }
            set
            {
                if ((yearFieldSpecified.Equals(value) != true))
                {
                    this.yearFieldSpecified = value;
                    this.OnPropertyChanged("YearSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("Name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                if ((amountField.Equals(value) != true))
                {
                    this.amountField = value;
                    this.OnPropertyChanged("Amount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                if ((amountFieldSpecified.Equals(value) != true))
                {
                    this.amountFieldSpecified = value;
                    this.OnPropertyChanged("AmountSpecified");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.flex2go.nl/2012-04")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.flex2go.nl/2012-04", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AvailablityType", Namespace = "http://www.flex2go.nl/2012-04")]
    public partial class AvailablityType : EntityBase<AvailablityType>
    {

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        private System.DateTime endDateField;

        private bool endDateFieldSpecified;

        private string roosterField;

        private short maximumHoursField;

        private bool maximumHoursFieldSpecified;

        private short minimumHoursField;

        private bool minimumHoursFieldSpecified;

        private System.DateTime mondayStartDateField;

        private bool mondayStartDateFieldSpecified;

        private System.DateTime mondayEndDateField;

        private bool mondayEndDateFieldSpecified;

        private System.DateTime tuesdayStartDateField;

        private bool tuesdayStartDateFieldSpecified;

        private System.DateTime tuesdayEndDateField;

        private bool tuesdayEndDateFieldSpecified;

        private System.DateTime wednesdayStartDateField;

        private bool wednesdayStartDateFieldSpecified;

        private System.DateTime wednesdayEndDateField;

        private bool wednesdayEndDateFieldSpecified;

        private System.DateTime thursdayStartDateField;

        private bool thursdayStartDateFieldSpecified;

        private System.DateTime thursdayEndDateField;

        private bool thursdayEndDateFieldSpecified;

        private System.DateTime fridayStartDateField;

        private bool fridayStartDateFieldSpecified;

        private System.DateTime fridayEndDateField;

        private bool fridayEndDateFieldSpecified;

        private System.DateTime saturdayStartDateField;

        private bool saturdayStartDateFieldSpecified;

        private System.DateTime saturdayEndDateField;

        private bool saturdayEndDateFieldSpecified;

        private System.DateTime sundayStartDateField;

        private bool sundayStartDateFieldSpecified;

        private System.DateTime sundayEndDateField;

        private bool sundayEndDateFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                if ((startDateField.Equals(value) != true))
                {
                    this.startDateField = value;
                    this.OnPropertyChanged("StartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                if ((startDateFieldSpecified.Equals(value) != true))
                {
                    this.startDateFieldSpecified = value;
                    this.OnPropertyChanged("StartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                if ((endDateField.Equals(value) != true))
                {
                    this.endDateField = value;
                    this.OnPropertyChanged("EndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EndDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                if ((endDateFieldSpecified.Equals(value) != true))
                {
                    this.endDateFieldSpecified = value;
                    this.OnPropertyChanged("EndDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rooster
        {
            get
            {
                return this.roosterField;
            }
            set
            {
                if ((this.roosterField != null))
                {
                    if ((roosterField.Equals(value) != true))
                    {
                        this.roosterField = value;
                        this.OnPropertyChanged("Rooster");
                    }
                }
                else
                {
                    this.roosterField = value;
                    this.OnPropertyChanged("Rooster");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short MaximumHours
        {
            get
            {
                return this.maximumHoursField;
            }
            set
            {
                if ((maximumHoursField.Equals(value) != true))
                {
                    this.maximumHoursField = value;
                    this.OnPropertyChanged("MaximumHours");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MaximumHoursSpecified
        {
            get
            {
                return this.maximumHoursFieldSpecified;
            }
            set
            {
                if ((maximumHoursFieldSpecified.Equals(value) != true))
                {
                    this.maximumHoursFieldSpecified = value;
                    this.OnPropertyChanged("MaximumHoursSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short MinimumHours
        {
            get
            {
                return this.minimumHoursField;
            }
            set
            {
                if ((minimumHoursField.Equals(value) != true))
                {
                    this.minimumHoursField = value;
                    this.OnPropertyChanged("MinimumHours");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MinimumHoursSpecified
        {
            get
            {
                return this.minimumHoursFieldSpecified;
            }
            set
            {
                if ((minimumHoursFieldSpecified.Equals(value) != true))
                {
                    this.minimumHoursFieldSpecified = value;
                    this.OnPropertyChanged("MinimumHoursSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MondayStartDate
        {
            get
            {
                return this.mondayStartDateField;
            }
            set
            {
                if ((mondayStartDateField.Equals(value) != true))
                {
                    this.mondayStartDateField = value;
                    this.OnPropertyChanged("MondayStartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MondayStartDateSpecified
        {
            get
            {
                return this.mondayStartDateFieldSpecified;
            }
            set
            {
                if ((mondayStartDateFieldSpecified.Equals(value) != true))
                {
                    this.mondayStartDateFieldSpecified = value;
                    this.OnPropertyChanged("MondayStartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 6)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MondayEndDate
        {
            get
            {
                return this.mondayEndDateField;
            }
            set
            {
                if ((mondayEndDateField.Equals(value) != true))
                {
                    this.mondayEndDateField = value;
                    this.OnPropertyChanged("MondayEndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MondayEndDateSpecified
        {
            get
            {
                return this.mondayEndDateFieldSpecified;
            }
            set
            {
                if ((mondayEndDateFieldSpecified.Equals(value) != true))
                {
                    this.mondayEndDateFieldSpecified = value;
                    this.OnPropertyChanged("MondayEndDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 7)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TuesdayStartDate
        {
            get
            {
                return this.tuesdayStartDateField;
            }
            set
            {
                if ((tuesdayStartDateField.Equals(value) != true))
                {
                    this.tuesdayStartDateField = value;
                    this.OnPropertyChanged("TuesdayStartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TuesdayStartDateSpecified
        {
            get
            {
                return this.tuesdayStartDateFieldSpecified;
            }
            set
            {
                if ((tuesdayStartDateFieldSpecified.Equals(value) != true))
                {
                    this.tuesdayStartDateFieldSpecified = value;
                    this.OnPropertyChanged("TuesdayStartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 8)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TuesdayEndDate
        {
            get
            {
                return this.tuesdayEndDateField;
            }
            set
            {
                if ((tuesdayEndDateField.Equals(value) != true))
                {
                    this.tuesdayEndDateField = value;
                    this.OnPropertyChanged("TuesdayEndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TuesdayEndDateSpecified
        {
            get
            {
                return this.tuesdayEndDateFieldSpecified;
            }
            set
            {
                if ((tuesdayEndDateFieldSpecified.Equals(value) != true))
                {
                    this.tuesdayEndDateFieldSpecified = value;
                    this.OnPropertyChanged("TuesdayEndDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 9)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WednesdayStartDate
        {
            get
            {
                return this.wednesdayStartDateField;
            }
            set
            {
                if ((wednesdayStartDateField.Equals(value) != true))
                {
                    this.wednesdayStartDateField = value;
                    this.OnPropertyChanged("WednesdayStartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WednesdayStartDateSpecified
        {
            get
            {
                return this.wednesdayStartDateFieldSpecified;
            }
            set
            {
                if ((wednesdayStartDateFieldSpecified.Equals(value) != true))
                {
                    this.wednesdayStartDateFieldSpecified = value;
                    this.OnPropertyChanged("WednesdayStartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 10)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WednesdayEndDate
        {
            get
            {
                return this.wednesdayEndDateField;
            }
            set
            {
                if ((wednesdayEndDateField.Equals(value) != true))
                {
                    this.wednesdayEndDateField = value;
                    this.OnPropertyChanged("WednesdayEndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WednesdayEndDateSpecified
        {
            get
            {
                return this.wednesdayEndDateFieldSpecified;
            }
            set
            {
                if ((wednesdayEndDateFieldSpecified.Equals(value) != true))
                {
                    this.wednesdayEndDateFieldSpecified = value;
                    this.OnPropertyChanged("WednesdayEndDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 11)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ThursdayStartDate
        {
            get
            {
                return this.thursdayStartDateField;
            }
            set
            {
                if ((thursdayStartDateField.Equals(value) != true))
                {
                    this.thursdayStartDateField = value;
                    this.OnPropertyChanged("ThursdayStartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ThursdayStartDateSpecified
        {
            get
            {
                return this.thursdayStartDateFieldSpecified;
            }
            set
            {
                if ((thursdayStartDateFieldSpecified.Equals(value) != true))
                {
                    this.thursdayStartDateFieldSpecified = value;
                    this.OnPropertyChanged("ThursdayStartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 12)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ThursdayEndDate
        {
            get
            {
                return this.thursdayEndDateField;
            }
            set
            {
                if ((thursdayEndDateField.Equals(value) != true))
                {
                    this.thursdayEndDateField = value;
                    this.OnPropertyChanged("ThursdayEndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ThursdayEndDateSpecified
        {
            get
            {
                return this.thursdayEndDateFieldSpecified;
            }
            set
            {
                if ((thursdayEndDateFieldSpecified.Equals(value) != true))
                {
                    this.thursdayEndDateFieldSpecified = value;
                    this.OnPropertyChanged("ThursdayEndDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 13)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FridayStartDate
        {
            get
            {
                return this.fridayStartDateField;
            }
            set
            {
                if ((fridayStartDateField.Equals(value) != true))
                {
                    this.fridayStartDateField = value;
                    this.OnPropertyChanged("FridayStartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FridayStartDateSpecified
        {
            get
            {
                return this.fridayStartDateFieldSpecified;
            }
            set
            {
                if ((fridayStartDateFieldSpecified.Equals(value) != true))
                {
                    this.fridayStartDateFieldSpecified = value;
                    this.OnPropertyChanged("FridayStartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 14)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FridayEndDate
        {
            get
            {
                return this.fridayEndDateField;
            }
            set
            {
                if ((fridayEndDateField.Equals(value) != true))
                {
                    this.fridayEndDateField = value;
                    this.OnPropertyChanged("FridayEndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FridayEndDateSpecified
        {
            get
            {
                return this.fridayEndDateFieldSpecified;
            }
            set
            {
                if ((fridayEndDateFieldSpecified.Equals(value) != true))
                {
                    this.fridayEndDateFieldSpecified = value;
                    this.OnPropertyChanged("FridayEndDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 15)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SaturdayStartDate
        {
            get
            {
                return this.saturdayStartDateField;
            }
            set
            {
                if ((saturdayStartDateField.Equals(value) != true))
                {
                    this.saturdayStartDateField = value;
                    this.OnPropertyChanged("SaturdayStartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SaturdayStartDateSpecified
        {
            get
            {
                return this.saturdayStartDateFieldSpecified;
            }
            set
            {
                if ((saturdayStartDateFieldSpecified.Equals(value) != true))
                {
                    this.saturdayStartDateFieldSpecified = value;
                    this.OnPropertyChanged("SaturdayStartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 16)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SaturdayEndDate
        {
            get
            {
                return this.saturdayEndDateField;
            }
            set
            {
                if ((saturdayEndDateField.Equals(value) != true))
                {
                    this.saturdayEndDateField = value;
                    this.OnPropertyChanged("SaturdayEndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SaturdayEndDateSpecified
        {
            get
            {
                return this.saturdayEndDateFieldSpecified;
            }
            set
            {
                if ((saturdayEndDateFieldSpecified.Equals(value) != true))
                {
                    this.saturdayEndDateFieldSpecified = value;
                    this.OnPropertyChanged("SaturdayEndDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 17)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SundayStartDate
        {
            get
            {
                return this.sundayStartDateField;
            }
            set
            {
                if ((sundayStartDateField.Equals(value) != true))
                {
                    this.sundayStartDateField = value;
                    this.OnPropertyChanged("SundayStartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SundayStartDateSpecified
        {
            get
            {
                return this.sundayStartDateFieldSpecified;
            }
            set
            {
                if ((sundayStartDateFieldSpecified.Equals(value) != true))
                {
                    this.sundayStartDateFieldSpecified = value;
                    this.OnPropertyChanged("SundayStartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 18)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SundayEndDate
        {
            get
            {
                return this.sundayEndDateField;
            }
            set
            {
                if ((sundayEndDateField.Equals(value) != true))
                {
                    this.sundayEndDateField = value;
                    this.OnPropertyChanged("SundayEndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SundayEndDateSpecified
        {
            get
            {
                return this.sundayEndDateFieldSpecified;
            }
            set
            {
                if ((sundayEndDateFieldSpecified.Equals(value) != true))
                {
                    this.sundayEndDateFieldSpecified = value;
                    this.OnPropertyChanged("SundayEndDateSpecified");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.flex2go.nl/2012-04")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.flex2go.nl/2012-04", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BankAccountExtraType", Namespace = "http://www.flex2go.nl/2012-04")]
    public partial class BankAccountExtraType : EntityBase<BankAccountExtraType>
    {

        private string bankAccountNumberField;

        private string paymentReferenceField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountNumber
        {
            get
            {
                return this.bankAccountNumberField;
            }
            set
            {
                if ((this.bankAccountNumberField != null))
                {
                    if ((bankAccountNumberField.Equals(value) != true))
                    {
                        this.bankAccountNumberField = value;
                        this.OnPropertyChanged("BankAccountNumber");
                    }
                }
                else
                {
                    this.bankAccountNumberField = value;
                    this.OnPropertyChanged("BankAccountNumber");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentReference
        {
            get
            {
                return this.paymentReferenceField;
            }
            set
            {
                if ((this.paymentReferenceField != null))
                {
                    if ((paymentReferenceField.Equals(value) != true))
                    {
                        this.paymentReferenceField = value;
                        this.OnPropertyChanged("PaymentReference");
                    }
                }
                else
                {
                    this.paymentReferenceField = value;
                    this.OnPropertyChanged("PaymentReference");
                }
            }
        }
    }
}
