// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.36516
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLasyLoading>False</EnableLasyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute("UserArea", Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserAreaType", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class UserAreaType : EntityBase<UserAreaType>
    {
        private HumanResourceAdditionalNLType humanResourceAdditionalNLField;

        private bool modelNameFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ModelNameSpecified
        {
            get
            {
                return this.modelNameFieldSpecified;
            }
            set
            {
                if ((modelNameFieldSpecified.Equals(value) != true))
                {
                    this.modelNameFieldSpecified = value;
                    this.OnPropertyChanged("ModelNameSpecified");
                }
            }
        }
        
        private string modelName;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Type = typeof(string), Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
        public string ModelName
        {
            get
            {
                return this.modelName;
            }
            set
            {
                this.modelName = value;
                this.OnPropertyChanged("ModelName");
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Type=typeof(HumanResourceAdditionalNLType), Namespace = "http://ns.setu.nl/2008-01", IsNullable = true)]
        public HumanResourceAdditionalNLType HumanResourceAdditionalNL
        {
            get
            {
                return this.humanResourceAdditionalNLField;
            }
            set
            {
                if ((this.humanResourceAdditionalNLField != null))
                {
                    if ((humanResourceAdditionalNLField.Equals(value) != true))
                    {
                        this.humanResourceAdditionalNLField = value;
                        this.OnPropertyChanged("HumanResourceAdditionalNL");
                    }
                }
                else
                {
                    this.humanResourceAdditionalNLField = value;
                    this.OnPropertyChanged("HumanResourceAdditionalNL");
                }
            }
        }

        private bool humanResourceAdditionalNLFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HumanResourceAdditionalNLSpecified
        {
            get
            {
                return this.humanResourceAdditionalNLFieldSpecified;
            }
            set
            {
                if ((humanResourceAdditionalNLFieldSpecified.Equals(value) != true))
                {
                    this.humanResourceAdditionalNLFieldSpecified = value;
                    this.OnPropertyChanged("HumanResourceAdditionalNLSpecified");
                }
            }
        }

        private HRXML.Net.V200701.HumanResourceAdditionalNLType humanResourceAdditionalNL2007Field;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(ElementName = "HumanResourceAdditionalNL", Type = typeof(HRXML.Net.V200701.HumanResourceAdditionalNLType), Namespace = "http://ns.setu.nl/2007-01", IsNullable = true)]
        public HRXML.Net.V200701.HumanResourceAdditionalNLType HumanResourceAdditionalNL2007
        {
            get
            {
                return this.humanResourceAdditionalNL2007Field;
            }
            set
            {
                if ((this.humanResourceAdditionalNL2007Field != null))
                {
                    if ((humanResourceAdditionalNL2007Field.Equals(value) != true))
                    {
                        this.humanResourceAdditionalNL2007Field = value;
                        this.OnPropertyChanged("HumanResourceAdditionalNL2007");
                    }
                }
                else
                {
                    this.humanResourceAdditionalNL2007Field = value;
                    this.OnPropertyChanged("HumanResourceAdditionalNL2007");
                }
            }
        }

        private bool humanResourceAdditionalNL2007FieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HumanResourceAdditionalNL2007Specified
        {
            get
            {
                return this.humanResourceAdditionalNL2007FieldSpecified;
            }
            set
            {
                if ((humanResourceAdditionalNL2007FieldSpecified.Equals(value) != true))
                {
                    this.humanResourceAdditionalNL2007FieldSpecified = value;
                    this.OnPropertyChanged("HumanResourceAdditionalNL2007Specified");
                }
            }
        }

        private AssignmentAdditionalNLType assignmentAdditionalNLField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://ns.setu.nl/2008-01", IsNullable = true)]
        public AssignmentAdditionalNLType AssignmentAdditionalNL
        {
            get
            {
                return this.assignmentAdditionalNLField;
            }
            set
            {
                if ((this.assignmentAdditionalNLField != null))
                {
                    if ((assignmentAdditionalNLField.Equals(value) != true))
                    {
                        this.assignmentAdditionalNLField = value;
                        this.OnPropertyChanged("AssignmentAdditionalNL");
                    }
                }
                else
                {
                    this.assignmentAdditionalNLField = value;
                    this.OnPropertyChanged("AssignmentAdditionalNL");
                }
            }
        }

        private bool assignmentAdditionalNLFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AssignmentAdditionalNLSpecified
        {
            get
            {
                return this.assignmentAdditionalNLFieldSpecified;
            }
            set
            {
                if ((assignmentAdditionalNLFieldSpecified.Equals(value) != true))
                {
                    this.assignmentAdditionalNLFieldSpecified = value;
                    this.OnPropertyChanged("AssignmentAdditionalNLSpecified");
                }
            }
        }

        private HRXML.Net.V200701.AssignmentAdditionalNLType assignmentAdditionalNL2007Field;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(ElementName = "AssignmentAdditionalNL", Type = typeof(HRXML.Net.V200701.AssignmentAdditionalNLType), Namespace = "http://ns.setu.nl/2007-01", IsNullable = true)]
        public HRXML.Net.V200701.AssignmentAdditionalNLType AssignmentAdditionalNL2007
        {
            get
            {
                return this.assignmentAdditionalNL2007Field;
            }
            set
            {
                if ((this.assignmentAdditionalNL2007Field != null))
                {
                    if ((assignmentAdditionalNL2007Field.Equals(value) != true))
                    {
                        this.assignmentAdditionalNL2007Field = value;
                        this.OnPropertyChanged("AssignmentAdditionalNL2007");
                    }
                }
                else
                {
                    this.assignmentAdditionalNL2007Field = value;
                    this.OnPropertyChanged("AssignmentAdditionalNL2007");
                }
            }
        }

        private bool assignmentAdditionalNL2007FieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AssignmentAdditionalNL2007Specified
        {
            get
            {
                return this.assignmentAdditionalNL2007FieldSpecified;
            }
            set
            {
                if ((assignmentAdditionalNL2007FieldSpecified.Equals(value) != true))
                {
                    this.assignmentAdditionalNL2007FieldSpecified = value;
                    this.OnPropertyChanged("AssignmentAdditionalNL2007Specified");
                }
            }
        }


        private NocoreHumanResourceType nocoreHumanResourceField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
        public NocoreHumanResourceType NocoreHumanResource
        {
            get
            {
                return this.nocoreHumanResourceField;
            }
            set
            {
                if ((this.nocoreHumanResourceField != null))
                {
                    if ((nocoreHumanResourceField.Equals(value) != true))
                    {
                        this.nocoreHumanResourceField = value;
                        this.OnPropertyChanged("NocoreHumanResource");
                    }
                }
                else
                {
                    this.nocoreHumanResourceField = value;
                    this.OnPropertyChanged("NocoreHumanResource");
                }
            }
        }

        private bool nocoreHumanResourceFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NocoreHumanResourceSpecified
        {
            get
            {
                return this.nocoreHumanResourceFieldSpecified;
            }
            set
            {
                if ((nocoreHumanResourceFieldSpecified.Equals(value) != true))
                {
                    this.nocoreHumanResourceFieldSpecified = value;
                    this.OnPropertyChanged("NocoreHumanResourceSpecified");
                }
            }
        }

        private NocoreStaffingOrganizationType nocoreStaffingOrganizationField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
        public NocoreStaffingOrganizationType NocoreStaffingOrganization
        {
            get
            {
                return this.nocoreStaffingOrganizationField;
            }
            set
            {
                if ((this.nocoreStaffingOrganizationField != null))
                {
                    if ((nocoreStaffingOrganizationField.Equals(value) != true))
                    {
                        this.nocoreStaffingOrganizationField = value;
                        this.OnPropertyChanged("NocoreStaffingOrganization");
                    }
                }
                else
                {
                    this.nocoreStaffingOrganizationField = value;
                    this.OnPropertyChanged("NocoreStaffingOrganization");
                }
            }
        }

        private bool nocoreStaffingOrganizationFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NocoreStaffingOrganizationSpecified
        {
            get
            {
                return this.nocoreStaffingOrganizationFieldSpecified;
            }
            set
            {
                if ((nocoreStaffingOrganizationFieldSpecified.Equals(value) != true))
                {
                    this.nocoreStaffingOrganizationFieldSpecified = value;
                    this.OnPropertyChanged("NocoreStaffingOrganizationSpecified");
                }
            }
        }

        private NocoreAssignmentType nocoreAssignmentField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
        public NocoreAssignmentType NocoreAssignment
        {
            get
            {
                return this.nocoreAssignmentField;
            }
            set
            {
                if ((this.nocoreAssignmentField != null))
                {
                    if ((nocoreAssignmentField.Equals(value) != true))
                    {
                        this.nocoreAssignmentField = value;
                        this.OnPropertyChanged("NocoreAssignment");
                    }
                }
                else
                {
                    this.nocoreAssignmentField = value;
                    this.OnPropertyChanged("NocoreAssignment");
                }
            }
        }

        private bool nocoreAssignmentFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NocoreAssignmentSpecified
        {
            get
            {
                return this.nocoreAssignmentFieldSpecified;
            }
            set
            {
                if ((nocoreAssignmentFieldSpecified.Equals(value) != true))
                {
                    this.nocoreAssignmentFieldSpecified = value;
                    this.OnPropertyChanged("NocoreAssignmentSpecified");
                }
            }
        }

        private NocoreResumeType nocoreResumeField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
        public NocoreResumeType NocoreResume
        {
            get
            {
                return this.nocoreResumeField;
            }
            set
            {
                if ((this.nocoreResumeField != null))
                {
                    if ((nocoreResumeField.Equals(value) != true))
                    {
                        this.nocoreResumeField = value;
                        this.OnPropertyChanged("NocoreResume");
                    }
                }
                else
                {
                    this.nocoreResumeField = value;
                    this.OnPropertyChanged("NocoreResume");
                }
            }
        }

        private bool nocoreResumeFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NocoreResumeSpecified
        {
            get
            {
                return this.nocoreResumeFieldSpecified;
            }
            set
            {
                if ((nocoreResumeFieldSpecified.Equals(value) != true))
                {
                    this.nocoreResumeFieldSpecified = value;
                    this.OnPropertyChanged("NocoreResumeSpecified");
                }
            }
        }

        private NocorePositionHistoryType nocorePositionHistoryField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
        public NocorePositionHistoryType NocorePositionHistory
        {
            get
            {
                return this.nocorePositionHistoryField;
            }
            set
            {
                if ((this.nocorePositionHistoryField != null))
                {
                    if ((nocorePositionHistoryField.Equals(value) != true))
                    {
                        this.nocorePositionHistoryField = value;
                        this.OnPropertyChanged("NocorePositionHistory");
                    }
                }
                else
                {
                    this.nocorePositionHistoryField = value;
                    this.OnPropertyChanged("NocorePositionHistory");
                }
            }
        }

        private bool nocorePositionHistoryFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NocorePositionHistorySpecified
        {
            get
            {
                return this.nocorePositionHistoryFieldSpecified;
            }
            set
            {
                if ((nocorePositionHistoryFieldSpecified.Equals(value) != true))
                {
                    this.nocorePositionHistoryFieldSpecified = value;
                    this.OnPropertyChanged("NocorePositionHistorySpecified");
                }
            }
        }

        private NocoreSchoolOrInstitutionType nocoreSchoolOrInstitutionField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
        public NocoreSchoolOrInstitutionType NocoreSchoolOrInstitution
        {
            get
            {
                return this.nocoreSchoolOrInstitutionField;
            }
            set
            {
                if ((this.nocoreSchoolOrInstitutionField != null))
                {
                    if ((nocoreSchoolOrInstitutionField.Equals(value) != true))
                    {
                        this.nocoreSchoolOrInstitutionField = value;
                        this.OnPropertyChanged("NocoreSchoolOrInstitution");
                    }
                }
                else
                {
                    this.nocoreSchoolOrInstitutionField = value;
                    this.OnPropertyChanged("NocoreSchoolOrInstitution");
                }
            }
        }

        private bool nocoreSchoolOrInstitutionFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NocoreSchoolOrInstitutionSpecified
        {
            get
            {
                return this.nocoreSchoolOrInstitutionFieldSpecified;
            }
            set
            {
                if ((nocoreSchoolOrInstitutionFieldSpecified.Equals(value) != true))
                {
                    this.nocoreSchoolOrInstitutionFieldSpecified = value;
                    this.OnPropertyChanged("NocoreSchoolOrInstitutionSpecified");
                }
            }
        }

        private NocorePositionOpeningType nocorePositionOpeningField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.nocore.nl/2010-10", IsNullable = true)]
        public NocorePositionOpeningType NocorePositionOpening
        {
            get
            {
                return this.nocorePositionOpeningField;
            }
            set
            {
                if ((this.nocorePositionOpeningField != null))
                {
                    if ((nocorePositionOpeningField.Equals(value) != true))
                    {
                        this.nocorePositionOpeningField = value;
                        this.OnPropertyChanged("NocorePositionOpening");
                    }
                }
                else
                {
                    this.nocorePositionOpeningField = value;
                    this.OnPropertyChanged("NocorePositionOpening");
                }
            }
        }

        private bool nocorePositionOpeningFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NocorePositionOpeningSpecified
        {
            get
            {
                return this.nocorePositionOpeningFieldSpecified;
            }
            set
            {
                if ((nocorePositionOpeningFieldSpecified.Equals(value) != true))
                {
                    this.nocorePositionOpeningFieldSpecified = value;
                    this.OnPropertyChanged("NocorePositionOpeningSpecified");
                }
            }
        }


        /* FlexGate */

        private FlexGateHumanResourceType flexGateHumanResourceField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.birdseyeview.nl/Flexgate/2011-05", IsNullable = true)]
        public FlexGateHumanResourceType FlexGateHumanResource
        {
            get
            {
                return this.flexGateHumanResourceField;
            }
            set
            {
                if ((this.flexGateHumanResourceField != null))
                {
                    if ((flexGateHumanResourceField.Equals(value) != true))
                    {
                        this.flexGateHumanResourceField = value;
                        this.OnPropertyChanged("FlexGateHumanResource");
                    }
                }
                else
                {
                    this.flexGateHumanResourceField = value;
                    this.OnPropertyChanged("FlexGateHumanResource");
                }
            }
        }

        private bool flexGateHumanResourceFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlexGateHumanResourceSpecified
        {
            get
            {
                return this.flexGateHumanResourceFieldSpecified;
            }
            set
            {
                if ((flexGateHumanResourceFieldSpecified.Equals(value) != true))
                {
                    this.flexGateHumanResourceFieldSpecified = value;
                    this.OnPropertyChanged("FlexGateHumanResourceSpecified");
                }
            }
        }

        private FlexGateStaffingOrganizationType flexGateStaffingOrganizationField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.birdseyeview.nl/Flexgate/2011-05", IsNullable = true)]
        public FlexGateStaffingOrganizationType FlexGateStaffingOrganization
        {
            get
            {
                return this.flexGateStaffingOrganizationField;
            }
            set
            {
                if ((this.flexGateStaffingOrganizationField != null))
                {
                    if ((flexGateStaffingOrganizationField.Equals(value) != true))
                    {
                        this.flexGateStaffingOrganizationField = value;
                        this.OnPropertyChanged("FlexGateStaffingOrganization");
                    }
                }
                else
                {
                    this.flexGateStaffingOrganizationField = value;
                    this.OnPropertyChanged("FlexGateStaffingOrganization");
                }
            }
        }

        private bool flexGateStaffingOrganizationFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlexGateStaffingOrganizationSpecified
        {
            get
            {
                return this.flexGateStaffingOrganizationFieldSpecified;
            }
            set
            {
                if ((flexGateStaffingOrganizationFieldSpecified.Equals(value) != true))
                {
                    this.flexGateStaffingOrganizationFieldSpecified = value;
                    this.OnPropertyChanged("FlexGateStaffingOrganizationSpecified");
                }
            }
        }

        private FlexGateAssignmentType flexGateAssignmentField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.birdseyeview.nl/Flexgate/2011-05", IsNullable = true)]
        public FlexGateAssignmentType FlexGateAssignment
        {
            get
            {
                return this.flexGateAssignmentField;
            }
            set
            {
                if ((this.flexGateAssignmentField != null))
                {
                    if ((flexGateAssignmentField.Equals(value) != true))
                    {
                        this.flexGateAssignmentField = value;
                        this.OnPropertyChanged("FlexGateAssignment");
                    }
                }
                else
                {
                    this.flexGateAssignmentField = value;
                    this.OnPropertyChanged("FlexGateAssignment");
                }
            }
        }

        private bool flexGateAssignmentFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlexGateAssignmentSpecified
        {
            get
            {
                return this.flexGateAssignmentFieldSpecified;
            }
            set
            {
                if ((flexGateAssignmentFieldSpecified.Equals(value) != true))
                {
                    this.flexGateAssignmentFieldSpecified = value;
                    this.OnPropertyChanged("FlexGateAssignmentSpecified");
                }
            }
        }

        private HumanResourceAdditionalMWType humanResourceAdditionalMWField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
        public HumanResourceAdditionalMWType HumanResourceAdditionalMW
        {
            get
            {
                return this.humanResourceAdditionalMWField;
            }
            set
            {
                if ((this.humanResourceAdditionalMWField != null))
                {
                    if ((humanResourceAdditionalMWField.Equals(value) != true))
                    {
                        this.humanResourceAdditionalMWField = value;
                        this.OnPropertyChanged("HumanResourceAdditionalMW");
                    }
                }
                else
                {
                    this.humanResourceAdditionalMWField = value;
                    this.OnPropertyChanged("HumanResourceAdditionalMW");
                }
            }
        }

        private bool humanResourceAdditionalMWFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HumanResourceAdditionalMWSpecified
        {
            get
            {
                return this.humanResourceAdditionalMWFieldSpecified;
            }
            set
            {
                if ((humanResourceAdditionalMWFieldSpecified.Equals(value) != true))
                {
                    this.humanResourceAdditionalMWFieldSpecified = value;
                    this.OnPropertyChanged("HumanResourceAdditionalMWSpecified");
                }
            }
        }

        private StaffingOrganizationAdditionalXXType staffingOrganizationAdditionalXXField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
        public StaffingOrganizationAdditionalXXType StaffingOrganizationAdditionalXX
        {
            get
            {
                return this.staffingOrganizationAdditionalXXField;
            }
            set
            {
                if ((this.staffingOrganizationAdditionalXXField != null))
                {
                    if ((staffingOrganizationAdditionalXXField.Equals(value) != true))
                    {
                        this.staffingOrganizationAdditionalXXField = value;
                        this.OnPropertyChanged("StaffingOrganizationAdditionalXX");
                    }
                }
                else
                {
                    this.staffingOrganizationAdditionalXXField = value;
                    this.OnPropertyChanged("StaffingOrganizationAdditionalXX");
                }
            }
        }

        private bool staffingOrganizationAdditionalXXFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StaffingOrganizationAdditionalXXSpecified
        {
            get
            {
                return this.staffingOrganizationAdditionalXXFieldSpecified;
            }
            set
            {
                if ((staffingOrganizationAdditionalXXFieldSpecified.Equals(value) != true))
                {
                    this.staffingOrganizationAdditionalXXFieldSpecified = value;
                    this.OnPropertyChanged("StaffingOrganizationAdditionalXXSpecified");
                }
            }
        }

        private AssignmentAdditionalMPType assignmentAdditionalMPField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://ns.xxcompany.nl/2010-01", IsNullable = true)]
        public AssignmentAdditionalMPType AssignmentAdditionalMP
        {
            get
            {
                return this.assignmentAdditionalMPField;
            }
            set
            {
                if ((this.assignmentAdditionalMPField != null))
                {
                    if ((assignmentAdditionalMPField.Equals(value) != true))
                    {
                        this.assignmentAdditionalMPField = value;
                        this.OnPropertyChanged("AssignmentAdditionalMP");
                    }
                }
                else
                {
                    this.assignmentAdditionalMPField = value;
                    this.OnPropertyChanged("AssignmentAdditionalMP");
                }
            }
        }

        private bool assignmentAdditionalMPFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AssignmentAdditionalMPSpecified
        {
            get
            {
                return this.assignmentAdditionalMPFieldSpecified;
            }
            set
            {
                if ((assignmentAdditionalMPFieldSpecified.Equals(value) != true))
                {
                    this.assignmentAdditionalMPFieldSpecified = value;
                    this.OnPropertyChanged("AssignmentAdditionalMPSpecified");
                }
            }
        }

        private TimecardAdditionalMPType timecardAdditionalMPField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
        public TimecardAdditionalMPType TimecardAdditionalMP
        {
            get
            {
                return this.timecardAdditionalMPField;
            }
            set
            {
                if ((this.timecardAdditionalMPField != null))
                {
                    if ((timecardAdditionalMPField.Equals(value) != true))
                    {
                        this.timecardAdditionalMPField = value;
                        this.OnPropertyChanged("TimecardAdditionalMP");
                    }
                }
                else
                {
                    this.timecardAdditionalMPField = value;
                    this.OnPropertyChanged("TimecardAdditionalMP");
                }
            }
        }

        private bool timecardAdditionalMPFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TimecardAdditionalMPSpecified
        {
            get
            {
                return this.timecardAdditionalMPFieldSpecified;
            }
            set
            {
                if ((timecardAdditionalMPFieldSpecified.Equals(value) != true))
                {
                    this.timecardAdditionalMPFieldSpecified = value;
                    this.OnPropertyChanged("TimecardAdditionalMPSpecified");
                }
            }
        }

        private TimecardAdditionalXXType timecardAdditionalXXField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
        public TimecardAdditionalXXType TimecardAdditionalXX
        {
            get
            {
                return this.timecardAdditionalXXField;
            }
            set
            {
                if ((this.timecardAdditionalXXField != null))
                {
                    if ((timecardAdditionalXXField.Equals(value) != true))
                    {
                        this.timecardAdditionalXXField = value;
                        this.OnPropertyChanged("TimecardAdditionalXX");
                    }
                }
                else
                {
                    this.timecardAdditionalXXField = value;
                    this.OnPropertyChanged("TimecardAdditionalXX");
                }
            }
        }

        private bool timecardAdditionalXXFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TimecardAdditionalXXSpecified
        {
            get
            {
                return this.timecardAdditionalXXFieldSpecified;
            }
            set
            {
                if ((timecardAdditionalXXFieldSpecified.Equals(value) != true))
                {
                    this.timecardAdditionalXXFieldSpecified = value;
                    this.OnPropertyChanged("TimecardAdditionalXXSpecified");
                }
            }
        }

        private Flex2GoTimecardType flex2GoTimecardField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.flex2go.nl/2016-06", IsNullable = true)]
        public Flex2GoTimecardType Flex2GoTimecard
        {
            get
            {
                return this.flex2GoTimecardField;
            }
            set
            {
                if ((this.flex2GoTimecardField != null))
                {
                    if ((flex2GoTimecardField.Equals(value) != true))
                    {
                        this.flex2GoTimecardField = value;
                        this.OnPropertyChanged("Flex2GoTimecard");
                    }
                }
                else
                {
                    this.flex2GoTimecardField = value;
                    this.OnPropertyChanged("Flex2GoTimecard");
                }
            }
        }

        private bool flex2GoTimecardFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Flex2GoTimecardSpecified
        {
            get
            {
                return this.flex2GoTimecardFieldSpecified;
            }
            set
            {
                if ((flex2GoTimecardFieldSpecified.Equals(value) != true))
                {
                    this.flex2GoTimecardFieldSpecified = value;
                    this.OnPropertyChanged("Flex2GoTimecardSpecified");
                }
            }
        }

        private Flex2GoHumanResourceType flex2GoHumanResourceTypeField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.flex2go.nl/2012-04", IsNullable = true)]
        public Flex2GoHumanResourceType Flex2GoHumanResource
        {
            get
            {
                return this.flex2GoHumanResourceTypeField;
            }
            set
            {
                if ((this.flex2GoHumanResourceTypeField != null))
                {
                    if ((flex2GoHumanResourceTypeField.Equals(value) != true))
                    {
                        this.flex2GoHumanResourceTypeField = value;
                        this.OnPropertyChanged("Flex2GoHumanResource");
                    }
                }
                else
                {
                    this.flex2GoHumanResourceTypeField = value;
                    this.OnPropertyChanged("Flex2GoHumanResource");
                }
            }
        }

        private bool flex2GoHumanResourceTypeFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Flex2GoHumanResourceSpecified
        {
            get
            {
                return this.flex2GoHumanResourceTypeFieldSpecified;
            }
            set
            {
                if ((flex2GoHumanResourceTypeFieldSpecified.Equals(value) != true))
                {
                    this.flex2GoHumanResourceTypeFieldSpecified = value;
                    this.OnPropertyChanged("Flex2GoHumanResourceSpecified");
                }
            }
        }

        private Flex2GoStaffingOrganizationType flex2GoStaffingOrganizationTypeField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.flex2go.nl/2012-04", IsNullable = true)]
        public Flex2GoStaffingOrganizationType Flex2GoStaffingOrganization
        {
            get
            {
                return this.flex2GoStaffingOrganizationTypeField;
            }
            set
            {
                if ((this.flex2GoStaffingOrganizationTypeField != null))
                {
                    if ((flex2GoStaffingOrganizationTypeField.Equals(value) != true))
                    {
                        this.flex2GoStaffingOrganizationTypeField = value;
                        this.OnPropertyChanged("Flex2GoStaffingOrganization");
                    }
                }
                else
                {
                    this.flex2GoStaffingOrganizationTypeField = value;
                    this.OnPropertyChanged("Flex2GoStaffingOrganization");
                }
            }
        }

        private bool flex2GoStaffingOrganizationTypeFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Flex2GoStaffingOrganizationSpecified
        {
            get
            {
                return this.flex2GoStaffingOrganizationTypeFieldSpecified;
            }
            set
            {
                if ((flex2GoStaffingOrganizationTypeFieldSpecified.Equals(value) != true))
                {
                    this.flex2GoStaffingOrganizationTypeFieldSpecified = value;
                    this.OnPropertyChanged("Flex2GoStaffingOrganizationSpecified");
                }
            }
        }

        private Flex2GoAssignmentType flex2GoAssignmentTypeField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.flex2go.nl/2016-06", IsNullable = true)]
        public Flex2GoAssignmentType Flex2GoAssignment
        {
            get
            {
                return this.flex2GoAssignmentTypeField;
            }
            set
            {
                if ((this.flex2GoAssignmentTypeField != null))
                {
                    if ((flex2GoAssignmentTypeField.Equals(value) != true))
                    {
                        this.flex2GoAssignmentTypeField = value;
                        this.OnPropertyChanged("Flex2GoAssignment");
                    }
                }
                else
                {
                    this.flex2GoAssignmentTypeField = value;
                    this.OnPropertyChanged("Flex2GoAssignment");
                }
            }
        }

        private bool flex2GoAssignmentTypeFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Flex2GoAssignmentSpecified
        {
            get
            {
                return this.flex2GoAssignmentTypeFieldSpecified;
            }
            set
            {
                if ((flex2GoAssignmentTypeFieldSpecified.Equals(value) != true))
                {
                    this.flex2GoAssignmentTypeFieldSpecified = value;
                    this.OnPropertyChanged("Flex2GoAssignmentSpecified");
                }
            }
        }

        private List<System.Xml.XmlElement> anyField;

        /// <summary>
        /// UserAreaType class constructor
        /// </summary>
        public UserAreaType()
        {
            this.anyField = new List<System.Xml.XmlElement>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<System.Xml.XmlElement> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                if ((this.anyField != null))
                {
                    if ((anyField.Equals(value) != true))
                    {
                        this.anyField = value;
                        this.OnPropertyChanged("Any");
                    }
                }
                else
                {
                    this.anyField = value;
                    this.OnPropertyChanged("Any");
                }
            }
        }

        private HumanResourceAdditionalMPType humanResourceAdditionalMPField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://ns.manpower.nl/2010-01", IsNullable = true)]
        public HumanResourceAdditionalMPType HumanResourceAdditionalMP
        {
            get
            {
                return this.humanResourceAdditionalMPField;
            }
            set
            {
                if ((this.humanResourceAdditionalMPField != null))
                {
                    if ((humanResourceAdditionalMPField.Equals(value) != true))
                    {
                        this.humanResourceAdditionalMPField = value;
                        this.OnPropertyChanged("HumanResourceAdditionalMP");
                    }
                }
                else
                {
                    this.humanResourceAdditionalMPField = value;
                    this.OnPropertyChanged("HumanResourceAdditionalMP");
                }
            }
        }

        private bool humanResourceAdditionalMPFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HumanResourceAdditionalMPSpecified
        {
            get
            {
                return this.humanResourceAdditionalMPFieldSpecified;
            }
            set
            {
                if ((humanResourceAdditionalMPFieldSpecified.Equals(value) != true))
                {
                    this.humanResourceAdditionalMPFieldSpecified = value;
                    this.OnPropertyChanged("HumanResourceAdditionalMPSpecified");
                }
            }
        }

        private UitzendmasterHumanResourceType uitzendmasterHumanResourceField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.combil.nl/2013-04", IsNullable = true)]
        public UitzendmasterHumanResourceType UitzendmasterHumanResource
        {
            get
            {
                return this.uitzendmasterHumanResourceField;
            }
            set
            {
                if ((this.uitzendmasterHumanResourceField != null))
                {
                    if ((uitzendmasterHumanResourceField.Equals(value) != true))
                    {
                        this.uitzendmasterHumanResourceField = value;
                        this.OnPropertyChanged("UitzendmasterHumanResource");
                    }
                }
                else
                {
                    this.uitzendmasterHumanResourceField = value;
                    this.OnPropertyChanged("UitzendmasterHumanResource");
                }
            }
        }

        private bool uitzendmasterHumanResourceFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UitzendmasterHumanResourceSpecified
        {
            get
            {
                return this.uitzendmasterHumanResourceFieldSpecified;
            }
            set
            {
                if ((uitzendmasterHumanResourceFieldSpecified.Equals(value) != true))
                {
                    this.uitzendmasterHumanResourceFieldSpecified = value;
                    this.OnPropertyChanged("UitzendmasterHumanResourceSpecified");
                }
            }
        }

        private UitzendmasterStaffingOrganizationType uitzendmasterStaffingOrganizationField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.combil.nl/2013-04", IsNullable = true)]
        public UitzendmasterStaffingOrganizationType UitzendmasterStaffingOrganization
        {
            get
            {
                return this.uitzendmasterStaffingOrganizationField;
            }
            set
            {
                if ((this.uitzendmasterStaffingOrganizationField != null))
                {
                    if ((uitzendmasterStaffingOrganizationField.Equals(value) != true))
                    {
                        this.uitzendmasterStaffingOrganizationField = value;
                        this.OnPropertyChanged("UitzendmasterStaffingOrganization");
                    }
                }
                else
                {
                    this.uitzendmasterStaffingOrganizationField = value;
                    this.OnPropertyChanged("UitzendmasterStaffingOrganization");
                }
            }
        }

        private bool uitzendmasterStaffingOrganizationFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UitzendmasterStaffingOrganizationSpecified
        {
            get
            {
                return this.uitzendmasterStaffingOrganizationFieldSpecified;
            }
            set
            {
                if ((uitzendmasterStaffingOrganizationFieldSpecified.Equals(value) != true))
                {
                    this.uitzendmasterStaffingOrganizationFieldSpecified = value;
                    this.OnPropertyChanged("UitzendmasterStaffingOrganizationSpecified");
                }
            }
        }

        private UitzendmasterAssignmentType uitzendmasterAssignmentField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.combil.nl/2013-04", IsNullable = true)]
        public UitzendmasterAssignmentType UitzendmasterAssignment
        {
            get
            {
                return this.uitzendmasterAssignmentField;
            }
            set
            {
                if ((this.uitzendmasterAssignmentField != null))
                {
                    if ((uitzendmasterAssignmentField.Equals(value) != true))
                    {
                        this.uitzendmasterAssignmentField = value;
                        this.OnPropertyChanged("UitzendmasterAssignment");
                    }
                }
                else
                {
                    this.uitzendmasterAssignmentField = value;
                    this.OnPropertyChanged("UitzendmasterAssignment");
                }
            }
        }

        private bool uitzendmasterAssignmentFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UitzendmasterAssignmentSpecified
        {
            get
            {
                return this.uitzendmasterAssignmentFieldSpecified;
            }
            set
            {
                if ((uitzendmasterAssignmentFieldSpecified.Equals(value) != true))
                {
                    this.uitzendmasterAssignmentFieldSpecified = value;
                    this.OnPropertyChanged("UitzendmasterAssignmentSpecified");
                }
            }
        }

        private AfasAssignmentType afasAssignmentField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.afas.nl/2013-10", IsNullable = true)]
        public AfasAssignmentType AfasAssignment
        {
            get
            {
                return this.afasAssignmentField;
            }
            set
            {
                if ((this.afasAssignmentField != null))
                {
                    if ((afasAssignmentField.Equals(value) != true))
                    {
                        this.afasAssignmentField = value;
                        this.OnPropertyChanged("AfasAssignment");
                    }
                }
                else
                {
                    this.afasAssignmentField = value;
                    this.OnPropertyChanged("AfasAssignment");
                }
            }
        }

        private bool afasAssignmentFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AfasAssignmentSpecified
        {
            get
            {
                return this.afasAssignmentFieldSpecified;
            }
            set
            {
                if ((afasAssignmentFieldSpecified.Equals(value) != true))
                {
                    this.afasAssignmentFieldSpecified = value;
                    this.OnPropertyChanged("AfasAssignmentSpecified");
                }
            }
        }

        private EasyFlexType easyFlexField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.easyflex.net/2015-05", IsNullable = true)]
        public EasyFlexType EasyFlex
        {
            get
            {
                return this.easyFlexField;
            }
            set
            {
                if ((this.easyFlexField != null))
                {
                    if ((easyFlexField.Equals(value) != true))
                    {
                        this.easyFlexField = value;
                        this.OnPropertyChanged("EasyFlex");
                    }
                }
                else
                {
                    this.easyFlexField = value;
                    this.OnPropertyChanged("EasyFlex");
                }
            }
        }

        private bool easyFlexFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EasyFlexSpecified
        {
            get
            {
                return this.easyFlexFieldSpecified;
            }
            set
            {
                if ((easyFlexFieldSpecified.Equals(value) != true))
                {
                    this.easyFlexFieldSpecified = value;
                    this.OnPropertyChanged("EasyFlexSpecified");
                }
            }
        }

        // FlexGo

        private FlexGoStaffingOrganizationType flexGoSOTypeField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.flex2go.nl/2015-12", IsNullable = true)]
        public FlexGoStaffingOrganizationType FlexGoStaffingOrganization
        {
            get
            {
                return this.flexGoSOTypeField;
            }
            set
            {
                if ((this.flexGoSOTypeField != null))
                {
                    if ((flexGoSOTypeField.Equals(value) != true))
                    {
                        this.flexGoSOTypeField = value;
                        this.OnPropertyChanged("FlexGoStaffingOrganization");
                    }
                }
                else
                {
                    this.flexGoSOTypeField = value;
                    this.OnPropertyChanged("FlexGoStaffingOrganization");
                }
            }
        }

        private bool flexGoStaffingOrganizationSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlexGoStaffingOrganizationSpecified
        {
            get
            {
                return this.flexGoStaffingOrganizationSpecified;
            }
            set
            {
                if ((flexGoStaffingOrganizationSpecified.Equals(value) != true))
                {
                    this.flexGoStaffingOrganizationSpecified = value;
                    this.OnPropertyChanged("FlexGoStaffingOrganizationSpecified");
                }
            }
        }

        private FlexGoHumanResourceType flexGoHumanResourceTypeField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.flex2go.nl/2015-12", IsNullable = true)]
        public FlexGoHumanResourceType FlexGoHumanResource
        {
            get
            {
                return this.flexGoHumanResourceTypeField;
            }
            set
            {
                if ((this.flexGoHumanResourceTypeField != null))
                {
                    if ((flexGoHumanResourceTypeField.Equals(value) != true))
                    {
                        this.flexGoHumanResourceTypeField = value;
                        this.OnPropertyChanged("FlexGoHumanResource");
                    }
                }
                else
                {
                    this.flexGoHumanResourceTypeField = value;
                    this.OnPropertyChanged("FlexGoHumanResource");
                }
            }
        }

        private bool flexGoHumanResourceSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlexGoHumanResourceSpecified
        {
            get
            {
                return this.flexGoHumanResourceSpecified;
            }
            set
            {
                if ((flexGoHumanResourceSpecified.Equals(value) != true))
                {
                    this.flexGoHumanResourceSpecified = value;
                    this.OnPropertyChanged("FlexGoHumanResourceSpecified");
                }
            }
        }


        private FlexGoAssignmentType flexGoAssignmentTypeField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.flex2go.nl/2015-12", IsNullable = true)]
        public FlexGoAssignmentType FlexGoAssignment
        {
            get
            {
                return this.flexGoAssignmentTypeField;
            }
            set
            {
                if ((this.flexGoAssignmentTypeField != null))
                {
                    if ((flexGoAssignmentTypeField.Equals(value) != true))
                    {
                        this.flexGoAssignmentTypeField = value;
                        this.OnPropertyChanged("FlexGoAssignment");
                    }
                }
                else
                {
                    this.flexGoAssignmentTypeField = value;
                    this.OnPropertyChanged("FlexGoAssignment");
                }
            }
        }

        private bool flexGoAssignmentSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlexGoAssignmentSpecified
        {
            get
            {
                return this.flexGoAssignmentSpecified;
            }
            set
            {
                if ((flexGoAssignmentSpecified.Equals(value) != true))
                {
                    this.flexGoAssignmentSpecified = value;
                    this.OnPropertyChanged("FlexGoAssignmentSpecified");
                }
            }
        }

        private ScabHumanResourceType scabHumanResourceTypeField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.scabadvies.nl/2016-05", IsNullable = true)]
        public ScabHumanResourceType ScabHumanResource
        {
            get
            {
                return this.scabHumanResourceTypeField;
            }
            set
            {
                if ((this.scabHumanResourceTypeField != null))
                {
                    if ((scabHumanResourceTypeField.Equals(value) != true))
                    {
                        this.scabHumanResourceTypeField = value;
                        this.OnPropertyChanged("ScabHumanResource");
                    }
                }
                else
                {
                    this.scabHumanResourceTypeField = value;
                    this.OnPropertyChanged("ScabHumanResource");
                }
            }
        }

        private bool scabHumanResourceTypeFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ScabHumanResourceSpecified
        {
            get
            {
                return this.scabHumanResourceTypeFieldSpecified;
            }
            set
            {
                if ((scabHumanResourceTypeFieldSpecified.Equals(value) != true))
                {
                    this.scabHumanResourceTypeFieldSpecified = value;
                    this.OnPropertyChanged("ScabHumanResourceSpecified");
                }
            }
        }

        private ScabAssignmentType scabAssignmentTypeField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false)]
        [XmlElementAttribute(Namespace = "http://www.scabadvies.nl/2016-05", IsNullable = true)]
        public ScabAssignmentType ScabAssignment
        {
            get
            {
                return this.scabAssignmentTypeField;
            }
            set
            {
                if ((this.scabAssignmentTypeField != null))
                {
                    if ((scabAssignmentTypeField.Equals(value) != true))
                    {
                        this.scabAssignmentTypeField = value;
                        this.OnPropertyChanged("ScabAssignment");
                    }
                }
                else
                {
                    this.scabAssignmentTypeField = value;
                    this.OnPropertyChanged("ScabAssignment");
                }
            }
        }

        private bool scabAssignmentTypeFieldSpecified;

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ScabAssignmentSpecified
        {
            get
            {
                return this.scabAssignmentTypeFieldSpecified;
            }
            set
            {
                if ((scabAssignmentTypeFieldSpecified.Equals(value) != true))
                {
                    this.scabAssignmentTypeFieldSpecified = value;
                    this.OnPropertyChanged("ScabAssignmentSpecified");
                }
            }
        }

    }

}
