// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.33213
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "USTierCoverage", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class USTierCoverage : EntityBase<USTierCoverage>
    {

        private USTierCoverageTransactionCode transactionCodeField;

        private bool transactionCodeFieldSpecified;

        private string electedPlanCodeField;

        private string groupNumberField;

        private USTierCoverageCOBRAStatus cOBRAStatusField;

        private System.DateTime startDateField;

        private USTierCoverageCOBRAInformation cOBRAInformationField;

        private System.DateTime endDateField;

        private bool endDateFieldSpecified;

        private List<USTierCoverageCoverageLevel> coverageLevelField;

        private List<USTierCoverageProvider> providerField;

        private System.DateTime planParticipationSuspensionDateField;

        private bool planParticipationSuspensionDateFieldSpecified;

        private System.DateTime enrollmentSignatureDateField;

        private bool enrollmentSignatureDateFieldSpecified;

        private CarrierData carrierField;

        private HSAVendorType hSAVendorField;

        private string eligibilityPostalCodeField;

        private IdCardData idCardField;

        private string eligibilityRegionField;

        private System.DateTime originalEffectiveDateField;

        private bool originalEffectiveDateFieldSpecified;

        private bool lateEntrantIndicatorField;

        private bool lateEntrantIndicatorFieldSpecified;

        private USTierCoveragePlanType typeField;

        /// <summary>
        /// USTierCoverage class constructor
        /// </summary>
        public USTierCoverage()
        {
            this.idCardField = new IdCardData();
            this.hSAVendorField = new HSAVendorType();
            this.carrierField = new CarrierData();
            this.providerField = new List<USTierCoverageProvider>();
            this.coverageLevelField = new List<USTierCoverageCoverageLevel>();
            this.cOBRAInformationField = new USTierCoverageCOBRAInformation();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageTransactionCode TransactionCode
        {
            get
            {
                return this.transactionCodeField;
            }
            set
            {
                if ((transactionCodeField.Equals(value) != true))
                {
                    this.transactionCodeField = value;
                    this.OnPropertyChanged("TransactionCode");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TransactionCodeSpecified
        {
            get
            {
                return this.transactionCodeFieldSpecified;
            }
            set
            {
                if ((transactionCodeFieldSpecified.Equals(value) != true))
                {
                    this.transactionCodeFieldSpecified = value;
                    this.OnPropertyChanged("TransactionCodeSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElectedPlanCode
        {
            get
            {
                return this.electedPlanCodeField;
            }
            set
            {
                if ((this.electedPlanCodeField != null))
                {
                    if ((electedPlanCodeField.Equals(value) != true))
                    {
                        this.electedPlanCodeField = value;
                        this.OnPropertyChanged("ElectedPlanCode");
                    }
                }
                else
                {
                    this.electedPlanCodeField = value;
                    this.OnPropertyChanged("ElectedPlanCode");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupNumber
        {
            get
            {
                return this.groupNumberField;
            }
            set
            {
                if ((this.groupNumberField != null))
                {
                    if ((groupNumberField.Equals(value) != true))
                    {
                        this.groupNumberField = value;
                        this.OnPropertyChanged("GroupNumber");
                    }
                }
                else
                {
                    this.groupNumberField = value;
                    this.OnPropertyChanged("GroupNumber");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageCOBRAStatus COBRAStatus
        {
            get
            {
                return this.cOBRAStatusField;
            }
            set
            {
                if ((cOBRAStatusField.Equals(value) != true))
                {
                    this.cOBRAStatusField = value;
                    this.OnPropertyChanged("COBRAStatus");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                if ((startDateField.Equals(value) != true))
                {
                    this.startDateField = value;
                    this.OnPropertyChanged("StartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageCOBRAInformation COBRAInformation
        {
            get
            {
                return this.cOBRAInformationField;
            }
            set
            {
                if ((this.cOBRAInformationField != null))
                {
                    if ((cOBRAInformationField.Equals(value) != true))
                    {
                        this.cOBRAInformationField = value;
                        this.OnPropertyChanged("COBRAInformation");
                    }
                }
                else
                {
                    this.cOBRAInformationField = value;
                    this.OnPropertyChanged("COBRAInformation");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 6)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                if ((endDateField.Equals(value) != true))
                {
                    this.endDateField = value;
                    this.OnPropertyChanged("EndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EndDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                if ((endDateFieldSpecified.Equals(value) != true))
                {
                    this.endDateFieldSpecified = value;
                    this.OnPropertyChanged("EndDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("CoverageLevel", Order = 7)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<USTierCoverageCoverageLevel> CoverageLevel
        {
            get
            {
                return this.coverageLevelField;
            }
            set
            {
                if ((this.coverageLevelField != null))
                {
                    if ((coverageLevelField.Equals(value) != true))
                    {
                        this.coverageLevelField = value;
                        this.OnPropertyChanged("CoverageLevel");
                    }
                }
                else
                {
                    this.coverageLevelField = value;
                    this.OnPropertyChanged("CoverageLevel");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Provider", Order = 8)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<USTierCoverageProvider> Provider
        {
            get
            {
                return this.providerField;
            }
            set
            {
                if ((this.providerField != null))
                {
                    if ((providerField.Equals(value) != true))
                    {
                        this.providerField = value;
                        this.OnPropertyChanged("Provider");
                    }
                }
                else
                {
                    this.providerField = value;
                    this.OnPropertyChanged("Provider");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 9)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PlanParticipationSuspensionDate
        {
            get
            {
                return this.planParticipationSuspensionDateField;
            }
            set
            {
                if ((planParticipationSuspensionDateField.Equals(value) != true))
                {
                    this.planParticipationSuspensionDateField = value;
                    this.OnPropertyChanged("PlanParticipationSuspensionDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PlanParticipationSuspensionDateSpecified
        {
            get
            {
                return this.planParticipationSuspensionDateFieldSpecified;
            }
            set
            {
                if ((planParticipationSuspensionDateFieldSpecified.Equals(value) != true))
                {
                    this.planParticipationSuspensionDateFieldSpecified = value;
                    this.OnPropertyChanged("PlanParticipationSuspensionDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 10)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EnrollmentSignatureDate
        {
            get
            {
                return this.enrollmentSignatureDateField;
            }
            set
            {
                if ((enrollmentSignatureDateField.Equals(value) != true))
                {
                    this.enrollmentSignatureDateField = value;
                    this.OnPropertyChanged("EnrollmentSignatureDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnrollmentSignatureDateSpecified
        {
            get
            {
                return this.enrollmentSignatureDateFieldSpecified;
            }
            set
            {
                if ((enrollmentSignatureDateFieldSpecified.Equals(value) != true))
                {
                    this.enrollmentSignatureDateFieldSpecified = value;
                    this.OnPropertyChanged("EnrollmentSignatureDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarrierData Carrier
        {
            get
            {
                return this.carrierField;
            }
            set
            {
                if ((this.carrierField != null))
                {
                    if ((carrierField.Equals(value) != true))
                    {
                        this.carrierField = value;
                        this.OnPropertyChanged("Carrier");
                    }
                }
                else
                {
                    this.carrierField = value;
                    this.OnPropertyChanged("Carrier");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSAVendorType HSAVendor
        {
            get
            {
                return this.hSAVendorField;
            }
            set
            {
                if ((this.hSAVendorField != null))
                {
                    if ((hSAVendorField.Equals(value) != true))
                    {
                        this.hSAVendorField = value;
                        this.OnPropertyChanged("HSAVendor");
                    }
                }
                else
                {
                    this.hSAVendorField = value;
                    this.OnPropertyChanged("HSAVendor");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EligibilityPostalCode
        {
            get
            {
                return this.eligibilityPostalCodeField;
            }
            set
            {
                if ((this.eligibilityPostalCodeField != null))
                {
                    if ((eligibilityPostalCodeField.Equals(value) != true))
                    {
                        this.eligibilityPostalCodeField = value;
                        this.OnPropertyChanged("EligibilityPostalCode");
                    }
                }
                else
                {
                    this.eligibilityPostalCodeField = value;
                    this.OnPropertyChanged("EligibilityPostalCode");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IdCardData IdCard
        {
            get
            {
                return this.idCardField;
            }
            set
            {
                if ((this.idCardField != null))
                {
                    if ((idCardField.Equals(value) != true))
                    {
                        this.idCardField = value;
                        this.OnPropertyChanged("IdCard");
                    }
                }
                else
                {
                    this.idCardField = value;
                    this.OnPropertyChanged("IdCard");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EligibilityRegion
        {
            get
            {
                return this.eligibilityRegionField;
            }
            set
            {
                if ((this.eligibilityRegionField != null))
                {
                    if ((eligibilityRegionField.Equals(value) != true))
                    {
                        this.eligibilityRegionField = value;
                        this.OnPropertyChanged("EligibilityRegion");
                    }
                }
                else
                {
                    this.eligibilityRegionField = value;
                    this.OnPropertyChanged("EligibilityRegion");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 16)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OriginalEffectiveDate
        {
            get
            {
                return this.originalEffectiveDateField;
            }
            set
            {
                if ((originalEffectiveDateField.Equals(value) != true))
                {
                    this.originalEffectiveDateField = value;
                    this.OnPropertyChanged("OriginalEffectiveDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OriginalEffectiveDateSpecified
        {
            get
            {
                return this.originalEffectiveDateFieldSpecified;
            }
            set
            {
                if ((originalEffectiveDateFieldSpecified.Equals(value) != true))
                {
                    this.originalEffectiveDateFieldSpecified = value;
                    this.OnPropertyChanged("OriginalEffectiveDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LateEntrantIndicator
        {
            get
            {
                return this.lateEntrantIndicatorField;
            }
            set
            {
                if ((lateEntrantIndicatorField.Equals(value) != true))
                {
                    this.lateEntrantIndicatorField = value;
                    this.OnPropertyChanged("LateEntrantIndicator");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LateEntrantIndicatorSpecified
        {
            get
            {
                return this.lateEntrantIndicatorFieldSpecified;
            }
            set
            {
                if ((lateEntrantIndicatorFieldSpecified.Equals(value) != true))
                {
                    this.lateEntrantIndicatorFieldSpecified = value;
                    this.OnPropertyChanged("LateEntrantIndicatorSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoveragePlanType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                if ((typeField.Equals(value) != true))
                {
                    this.typeField = value;
                    this.OnPropertyChanged("type");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum USTierCoverageTransactionCode
    {

        /// <remarks/>
        Add,

        /// <remarks/>
        Audit,

        /// <remarks/>
        Change,

        /// <remarks/>
        Correction,

        /// <remarks/>
        Delete,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Employee Information Not Available")]
        EmployeeInformationNotAvailable,

        /// <remarks/>
        Reinstatement,

        /// <remarks/>
        Termination,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum USTierCoverageCOBRAStatus
    {

        /// <remarks/>
        COBRA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("non-COBRA")]
        nonCOBRA,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "USTierCoverageCOBRAInformation", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class USTierCoverageCOBRAInformation : EntityBase<USTierCoverageCOBRAInformation>
    {

        private System.DateTime cOBRAStartDateField;

        private bool cOBRAStartDateFieldSpecified;

        private System.DateTime cOBRAEndDateField;

        private bool cOBRAEndDateFieldSpecified;

        private System.DateTime paidThroughDateField;

        private bool paidThroughDateFieldSpecified;

        private System.DateTime qualifyingEventDateField;

        private bool qualifyingEventDateFieldSpecified;

        private USTierCoverageCOBRAInformationQualifyingEventCode qualifyingEventCodeField;

        private bool qualifyingEventCodeFieldSpecified;

        private string additionalQualifyingEventDataField;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime COBRAStartDate
        {
            get
            {
                return this.cOBRAStartDateField;
            }
            set
            {
                if ((cOBRAStartDateField.Equals(value) != true))
                {
                    this.cOBRAStartDateField = value;
                    this.OnPropertyChanged("COBRAStartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool COBRAStartDateSpecified
        {
            get
            {
                return this.cOBRAStartDateFieldSpecified;
            }
            set
            {
                if ((cOBRAStartDateFieldSpecified.Equals(value) != true))
                {
                    this.cOBRAStartDateFieldSpecified = value;
                    this.OnPropertyChanged("COBRAStartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime COBRAEndDate
        {
            get
            {
                return this.cOBRAEndDateField;
            }
            set
            {
                if ((cOBRAEndDateField.Equals(value) != true))
                {
                    this.cOBRAEndDateField = value;
                    this.OnPropertyChanged("COBRAEndDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool COBRAEndDateSpecified
        {
            get
            {
                return this.cOBRAEndDateFieldSpecified;
            }
            set
            {
                if ((cOBRAEndDateFieldSpecified.Equals(value) != true))
                {
                    this.cOBRAEndDateFieldSpecified = value;
                    this.OnPropertyChanged("COBRAEndDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaidThroughDate
        {
            get
            {
                return this.paidThroughDateField;
            }
            set
            {
                if ((paidThroughDateField.Equals(value) != true))
                {
                    this.paidThroughDateField = value;
                    this.OnPropertyChanged("PaidThroughDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PaidThroughDateSpecified
        {
            get
            {
                return this.paidThroughDateFieldSpecified;
            }
            set
            {
                if ((paidThroughDateFieldSpecified.Equals(value) != true))
                {
                    this.paidThroughDateFieldSpecified = value;
                    this.OnPropertyChanged("PaidThroughDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime QualifyingEventDate
        {
            get
            {
                return this.qualifyingEventDateField;
            }
            set
            {
                if ((qualifyingEventDateField.Equals(value) != true))
                {
                    this.qualifyingEventDateField = value;
                    this.OnPropertyChanged("QualifyingEventDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool QualifyingEventDateSpecified
        {
            get
            {
                return this.qualifyingEventDateFieldSpecified;
            }
            set
            {
                if ((qualifyingEventDateFieldSpecified.Equals(value) != true))
                {
                    this.qualifyingEventDateFieldSpecified = value;
                    this.OnPropertyChanged("QualifyingEventDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageCOBRAInformationQualifyingEventCode QualifyingEventCode
        {
            get
            {
                return this.qualifyingEventCodeField;
            }
            set
            {
                if ((qualifyingEventCodeField.Equals(value) != true))
                {
                    this.qualifyingEventCodeField = value;
                    this.OnPropertyChanged("QualifyingEventCode");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool QualifyingEventCodeSpecified
        {
            get
            {
                return this.qualifyingEventCodeFieldSpecified;
            }
            set
            {
                if ((qualifyingEventCodeFieldSpecified.Equals(value) != true))
                {
                    this.qualifyingEventCodeFieldSpecified = value;
                    this.OnPropertyChanged("QualifyingEventCodeSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalQualifyingEventData
        {
            get
            {
                return this.additionalQualifyingEventDataField;
            }
            set
            {
                if ((this.additionalQualifyingEventDataField != null))
                {
                    if ((additionalQualifyingEventDataField.Equals(value) != true))
                    {
                        this.additionalQualifyingEventDataField = value;
                        this.OnPropertyChanged("AdditionalQualifyingEventData");
                    }
                }
                else
                {
                    this.additionalQualifyingEventDataField = value;
                    this.OnPropertyChanged("AdditionalQualifyingEventData");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum USTierCoverageCOBRAInformationQualifyingEventCode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Bankruptcy of a Retired Employee")]
        BankruptcyofaRetiredEmployee,

        /// <remarks/>
        Death,

        /// <remarks/>
        Divorce,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ineligible Child")]
        IneligibleChild,

        /// <remarks/>
        Medicare,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Reduction of work hours")]
        Reductionofworkhours,

        /// <remarks/>
        Separation,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Termination of Employment")]
        TerminationofEmployment,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "USTierCoverageCoverageLevel", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class USTierCoverageCoverageLevel : EntityBase<USTierCoverageCoverageLevel>
    {

        private string coverageLevelCodeField;

        private System.DateTime startDateField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoverageLevelCode
        {
            get
            {
                return this.coverageLevelCodeField;
            }
            set
            {
                if ((this.coverageLevelCodeField != null))
                {
                    if ((coverageLevelCodeField.Equals(value) != true))
                    {
                        this.coverageLevelCodeField = value;
                        this.OnPropertyChanged("CoverageLevelCode");
                    }
                }
                else
                {
                    this.coverageLevelCodeField = value;
                    this.OnPropertyChanged("CoverageLevelCode");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                if ((startDateField.Equals(value) != true))
                {
                    this.startDateField = value;
                    this.OnPropertyChanged("StartDate");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "USTierCoverageProvider", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class USTierCoverageProvider : EntityBase<USTierCoverageProvider>
    {

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        private object itemField;

        private List<ContactMethodType> contactInformationField;

        private USTierCoverageProviderProviderId providerIdField;

        private USTierCoverageProviderProviderRelationshipCode providerRelationshipCodeField;

        private bool providerRelationshipCodeFieldSpecified;

        private USTierCoverageProviderProviderChangeReason providerChangeReasonField;

        private bool providerChangeReasonFieldSpecified;

        private USTierCoverageProviderProviderType providerTypeField;

        private bool providerTypeFieldSpecified;

        private USTierCoverageProviderProviderTypeQualifier providerTypeQualifierField;

        private bool providerTypeQualifierFieldSpecified;

        /// <summary>
        /// USTierCoverageProvider class constructor
        /// </summary>
        public USTierCoverageProvider()
        {
            this.providerIdField = new USTierCoverageProviderProviderId();
            this.contactInformationField = new List<ContactMethodType>();
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                if ((startDateField.Equals(value) != true))
                {
                    this.startDateField = value;
                    this.OnPropertyChanged("StartDate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                if ((startDateFieldSpecified.Equals(value) != true))
                {
                    this.startDateFieldSpecified = value;
                    this.OnPropertyChanged("StartDateSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("OrganizationName", typeof(string), Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("PersonName", typeof(PersonNameType), Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                if ((this.itemField != null))
                {
                    if ((itemField.Equals(value) != true))
                    {
                        this.itemField = value;
                        this.OnPropertyChanged("Item");
                    }
                }
                else
                {
                    this.itemField = value;
                    this.OnPropertyChanged("Item");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ContactInformation", Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ContactMethodType> ContactInformation
        {
            get
            {
                return this.contactInformationField;
            }
            set
            {
                if ((this.contactInformationField != null))
                {
                    if ((contactInformationField.Equals(value) != true))
                    {
                        this.contactInformationField = value;
                        this.OnPropertyChanged("ContactInformation");
                    }
                }
                else
                {
                    this.contactInformationField = value;
                    this.OnPropertyChanged("ContactInformation");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageProviderProviderId ProviderId
        {
            get
            {
                return this.providerIdField;
            }
            set
            {
                if ((this.providerIdField != null))
                {
                    if ((providerIdField.Equals(value) != true))
                    {
                        this.providerIdField = value;
                        this.OnPropertyChanged("ProviderId");
                    }
                }
                else
                {
                    this.providerIdField = value;
                    this.OnPropertyChanged("ProviderId");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageProviderProviderRelationshipCode ProviderRelationshipCode
        {
            get
            {
                return this.providerRelationshipCodeField;
            }
            set
            {
                if ((providerRelationshipCodeField.Equals(value) != true))
                {
                    this.providerRelationshipCodeField = value;
                    this.OnPropertyChanged("ProviderRelationshipCode");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProviderRelationshipCodeSpecified
        {
            get
            {
                return this.providerRelationshipCodeFieldSpecified;
            }
            set
            {
                if ((providerRelationshipCodeFieldSpecified.Equals(value) != true))
                {
                    this.providerRelationshipCodeFieldSpecified = value;
                    this.OnPropertyChanged("ProviderRelationshipCodeSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageProviderProviderChangeReason ProviderChangeReason
        {
            get
            {
                return this.providerChangeReasonField;
            }
            set
            {
                if ((providerChangeReasonField.Equals(value) != true))
                {
                    this.providerChangeReasonField = value;
                    this.OnPropertyChanged("ProviderChangeReason");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProviderChangeReasonSpecified
        {
            get
            {
                return this.providerChangeReasonFieldSpecified;
            }
            set
            {
                if ((providerChangeReasonFieldSpecified.Equals(value) != true))
                {
                    this.providerChangeReasonFieldSpecified = value;
                    this.OnPropertyChanged("ProviderChangeReasonSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageProviderProviderType providerType
        {
            get
            {
                return this.providerTypeField;
            }
            set
            {
                if ((providerTypeField.Equals(value) != true))
                {
                    this.providerTypeField = value;
                    this.OnPropertyChanged("providerType");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool providerTypeSpecified
        {
            get
            {
                return this.providerTypeFieldSpecified;
            }
            set
            {
                if ((providerTypeFieldSpecified.Equals(value) != true))
                {
                    this.providerTypeFieldSpecified = value;
                    this.OnPropertyChanged("providerTypeSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageProviderProviderTypeQualifier providerTypeQualifier
        {
            get
            {
                return this.providerTypeQualifierField;
            }
            set
            {
                if ((providerTypeQualifierField.Equals(value) != true))
                {
                    this.providerTypeQualifierField = value;
                    this.OnPropertyChanged("providerTypeQualifier");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool providerTypeQualifierSpecified
        {
            get
            {
                return this.providerTypeQualifierFieldSpecified;
            }
            set
            {
                if ((providerTypeQualifierFieldSpecified.Equals(value) != true))
                {
                    this.providerTypeQualifierFieldSpecified = value;
                    this.OnPropertyChanged("providerTypeQualifierSpecified");
                }
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "USTierCoverageProviderProviderId", Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public partial class USTierCoverageProviderProviderId : EntityBase<USTierCoverageProviderProviderId>
    {

        private USTierCoverageProviderProviderIdProviderIdQualifier providerIdQualifierField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USTierCoverageProviderProviderIdProviderIdQualifier providerIdQualifier
        {
            get
            {
                return this.providerIdQualifierField;
            }
            set
            {
                if ((providerIdQualifierField.Equals(value) != true))
                {
                    this.providerIdQualifierField = value;
                    this.OnPropertyChanged("providerIdQualifier");
                }
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((this.valueField != null))
                {
                    if ((valueField.Equals(value) != true))
                    {
                        this.valueField = value;
                        this.OnPropertyChanged("Value");
                    }
                }
                else
                {
                    this.valueField = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum USTierCoverageProviderProviderIdProviderIdQualifier
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Social Security Number")]
        SocialSecurityNumber,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Federal Taxpayer Identification Number")]
        FederalTaxpayerIdentificationNumber,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("HCFA National Provider Identifier")]
        HCFANationalProviderIdentifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mutually Defined")]
        MutuallyDefined,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum USTierCoverageProviderProviderRelationshipCode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Established Patient")]
        EstablishedPatient,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not Established Patient")]
        NotEstablishedPatient,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not Known")]
        NotKnown,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum USTierCoverageProviderProviderChangeReason
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Appointment Times Not Met in a Timely Manner")]
        AppointmentTimesNotMetinaTimelyManner,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Current Customer Information File in Error")]
        CurrentCustomerInformationFileinError,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dissatisfaction with Medical Care/Services Rendered")]
        DissatisfactionwithMedicalCareServicesRendered,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dissatisfaction with Office Staff")]
        DissatisfactionwithOfficeStaff,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dissatisfaction with Physician\'s Referral Policy")]
        DissatisfactionwithPhysiciansReferralPolicy,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dissatisfied with Office Hours")]
        DissatisfiedwithOfficeHours,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Inconvenient Office Location")]
        InconvenientOfficeLocation,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Less Respect/Attention/Time Given Than to Other Patients")]
        LessRespectAttentionTimeGivenThantoOtherPatients,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No Reason Given")]
        NoReasonGiven,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Patient Moved to a New Location")]
        PatientMovedtoaNewLocation,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Plan Change")]
        PlanChange,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Unable to Scheduled Appointments in a Timely Manner")]
        UnabletoScheduledAppointmentsinaTimelyManner,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voluntary Withdrawal")]
        VoluntaryWithdrawal,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dissatisfaction with Medical Care or Services Rendered")]
        DissatisfactionwithMedicalCareorServicesRendered,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dissatisfaction with Physician Referral Policy")]
        DissatisfactionwithPhysicianReferralPolicy,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Less Respect or Attention or Time Given Than to Other Patients")]
        LessRespectorAttentionorTimeGivenThantoOtherPatients,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum USTierCoverageProviderProviderType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Obstetrics and Gynecology Facility")]
        ObstetricsandGynecologyFacility,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Doctor of Optometry")]
        DoctorofOptometry,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Primary Care Provider")]
        PrimaryCareProvider,

        /// <remarks/>
        Pharmacy,

        /// <remarks/>
        Dentist,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Managed Care Organization")]
        ManagedCareOrganization,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum USTierCoverageProviderProviderTypeQualifier
    {

        /// <remarks/>
        Person,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Non Person Entity")]
        NonPersonEntity,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ns.hr-xml.org/2007-04-15")]
    public enum USTierCoveragePlanType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24 Care")]
        Item24Care,

        /// <remarks/>
        Dental,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dental Capitation")]
        DentalCapitation,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Exclusive Provider Organization")]
        ExclusiveProviderOrganization,

        /// <remarks/>
        Health,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Health Maintenance Organization")]
        HealthMaintenanceOrganization,

        /// <remarks/>
        Hearing,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Long Term Care")]
        LongTermCare,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Long Term Disability")]
        LongTermDisability,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mail Order Drug")]
        MailOrderDrug,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Major Medical")]
        MajorMedical,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Risk")]
        MedicareRisk,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mental Health")]
        MentalHealth,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Point of Service")]
        PointofService,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Preferred Provider Organization")]
        PreferredProviderOrganization,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Prescription Drug")]
        PrescriptionDrug,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Preventative Care")]
        PreventativeCare,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Short Term Disability")]
        ShortTermDisability,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Utilization Review")]
        UtilizationReview,

        /// <remarks/>
        Vision,
    }
}
