// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.36516
//    <NameSpace>HRXML.Net</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLasyLoading>False</EnableLasyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HRXML.Net {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.setu.nl/2008-01")]
    [System.Xml.Serialization.XmlRootAttribute("AssignmentAdditionalNL", Namespace="http://ns.setu.nl/2008-01", IsNullable=false)]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssignmentAdditionalNLType", Namespace="http://ns.setu.nl/2008-01")]
    public partial class AssignmentAdditionalNLType : EntityBase<AssignmentAdditionalNLType> {
        
        private EntityIdType procurementOrderIdField;
        
        private string jobTitleField;
        
        private string jobIdField;
        
        private string jobGroupField;
        
        private List<StaffingWorkSiteType> staffingWorkSiteField;
        
        private string shiftTypeField;
        
        private CLAReferenceType cLAReferenceField;
        
        private string reasonOfChangeField;
        
        /// <summary>
        /// AssignmentAdditionalNLType class constructor
        /// </summary>
        public AssignmentAdditionalNLType() {
            this.staffingWorkSiteField = new List<StaffingWorkSiteType>();
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityIdType ProcurementOrderId {
            get {
                return this.procurementOrderIdField;
            }
            set {
                if ((this.procurementOrderIdField != null)) {
                    if ((procurementOrderIdField.Equals(value) != true)) {
                        this.procurementOrderIdField = value;
                        this.OnPropertyChanged("ProcurementOrderId");
                    }
                }
                else {
                    this.procurementOrderIdField = value;
                    this.OnPropertyChanged("ProcurementOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                if ((this.jobTitleField != null)) {
                    if ((jobTitleField.Equals(value) != true)) {
                        this.jobTitleField = value;
                        this.OnPropertyChanged("JobTitle");
                    }
                }
                else {
                    this.jobTitleField = value;
                    this.OnPropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobId {
            get {
                return this.jobIdField;
            }
            set {
                if ((this.jobIdField != null)) {
                    if ((jobIdField.Equals(value) != true)) {
                        this.jobIdField = value;
                        this.OnPropertyChanged("JobId");
                    }
                }
                else {
                    this.jobIdField = value;
                    this.OnPropertyChanged("JobId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobGroup {
            get {
                return this.jobGroupField;
            }
            set {
                if ((this.jobGroupField != null)) {
                    if ((jobGroupField.Equals(value) != true)) {
                        this.jobGroupField = value;
                        this.OnPropertyChanged("JobGroup");
                    }
                }
                else {
                    this.jobGroupField = value;
                    this.OnPropertyChanged("JobGroup");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("StaffingWorkSite")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<StaffingWorkSiteType> StaffingWorkSite {
            get {
                return this.staffingWorkSiteField;
            }
            set {
                if ((this.staffingWorkSiteField != null)) {
                    if ((staffingWorkSiteField.Equals(value) != true)) {
                        this.staffingWorkSiteField = value;
                        this.OnPropertyChanged("StaffingWorkSite");
                    }
                }
                else {
                    this.staffingWorkSiteField = value;
                    this.OnPropertyChanged("StaffingWorkSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShiftType {
            get {
                return this.shiftTypeField;
            }
            set {
                if ((this.shiftTypeField != null)) {
                    if ((shiftTypeField.Equals(value) != true)) {
                        this.shiftTypeField = value;
                        this.OnPropertyChanged("ShiftType");
                    }
                }
                else {
                    this.shiftTypeField = value;
                    this.OnPropertyChanged("ShiftType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CLAReferenceType CLAReference {
            get {
                return this.cLAReferenceField;
            }
            set {
                if ((this.cLAReferenceField != null)) {
                    if ((cLAReferenceField.Equals(value) != true)) {
                        this.cLAReferenceField = value;
                        this.OnPropertyChanged("CLAReference");
                    }
                }
                else {
                    this.cLAReferenceField = value;
                    this.OnPropertyChanged("CLAReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonOfChange {
            get {
                return this.reasonOfChangeField;
            }
            set {
                if ((this.reasonOfChangeField != null)) {
                    if ((reasonOfChangeField.Equals(value) != true)) {
                        this.reasonOfChangeField = value;
                        this.OnPropertyChanged("ReasonOfChange");
                    }
                }
                else {
                    this.reasonOfChangeField = value;
                    this.OnPropertyChanged("ReasonOfChange");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.setu.nl/2008-01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ns.setu.nl/2008-01", IsNullable=true)]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLAReferenceType", Namespace="http://ns.setu.nl/2008-01")]
    public partial class CLAReferenceType : EntityBase<CLAReferenceType> {
        
        private string descriptionField;
        
        private string cLAIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                if ((this.descriptionField != null)) {
                    if ((descriptionField.Equals(value) != true)) {
                        this.descriptionField = value;
                        this.OnPropertyChanged("Description");
                    }
                }
                else {
                    this.descriptionField = value;
                    this.OnPropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLAId {
            get {
                return this.cLAIdField;
            }
            set {
                if ((this.cLAIdField != null)) {
                    if ((cLAIdField.Equals(value) != true)) {
                        this.cLAIdField = value;
                        this.OnPropertyChanged("CLAId");
                    }
                }
                else {
                    this.cLAIdField = value;
                    this.OnPropertyChanged("CLAId");
                }
            }
        }
    }
}
